<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Mahasiswa_jumlah_mahasiswa</name>
   <tag></tag>
   <elementGuidId>dd018bba-ddc5-4516-bfb8-a78522a5bddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#penunjang_mahasiswa_A</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='penunjang_mahasiswa_A']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#penunjang_mahasiswa_A</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95c64c94-7f13-42f7-893a-cf82c5394bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjang_mahasiswa_A</value>
      <webElementGuid>d3fab05d-b042-422d-b440-701abd46881d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_mahasiswa</value>
      <webElementGuid>796f75a8-47e5-40c6-bc22-600a96f9b343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02e5dbb1-d182-45aa-9186-9ec7b6341592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>19cf24b3-a02c-400f-bc82-2b73f2a041a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b96a1a48-aff7-4295-9366-a4865cb5ce2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjang_mahasiswa_A&quot;)</value>
      <webElementGuid>1b7970ee-7719-4059-941a-ef689d90b2a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='penunjang_mahasiswa_A']</value>
      <webElementGuid>af776f7a-4cf4-4b0a-a5c9-742fa32b4152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_A']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>908520d0-9846-470e-be3d-9d31286a336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0782aea0-cc34-482f-8664-ce3c865fb9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'penunjang_mahasiswa_A' and @name = 'jumlah_mahasiswa' and @type = 'number']</value>
      <webElementGuid>1717cdbd-029a-4f48-9bce-b877235d082c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
