<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files</name>
   <tag></tag>
   <elementGuidId>b6182b92-8bb8-4138-93c6-293d32c4754a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtnPenelitianE-29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtnPenelitianE-29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Files&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c719f67-cde2-4292-ac38-55afc9c0c2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b3efb6a-8c70-4766-9d8c-fb44de0c8c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtnPenelitianE-29</value>
      <webElementGuid>40d7ec7b-7f2c-453b-a14a-fd82cfa48f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>959bd6b2-8af1-45c9-b36e-193ebbafd105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>bfb81201-ebe2-4572-80e6-e06ed3edeb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtnPenelitianE-29&quot;)</value>
      <webElementGuid>b50a72b1-80d6-4bcd-a9ab-5a32678bf285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtnPenelitianE-29']</value>
      <webElementGuid>206b0d86-8877-4bf5-b6d4-fac0b0984966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenelitian_E-29']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>cf35c388-3d74-4def-a23a-98d8727cfddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti kontrak penerbitan jika masih naik cetak'])[5]/following::button[1]</value>
      <webElementGuid>488df83f-3185-4bcc-8a19-02062726407e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buku yang sudah terbit'])[5]/following::button[1]</value>
      <webElementGuid>95245d61-8a3a-4691-abad-2ed3ae96f78e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[9]/preceding::button[1]</value>
      <webElementGuid>45230af1-27ff-41fe-9fc9-68b048d97af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>442b861f-ec0d-4b91-aed1-f80057fb8ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtnPenelitianE-29' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>94406c7c-eed1-4a9e-97b1-fe62725c5706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
