<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload                              _8f5048</name>
   <tag></tag>
   <elementGuidId>8a56b77d-4cf3-4016-9b5c-bd63192fd947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadPenelitianM-45</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUploadPenelitianM-45']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload Lampiran&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d76851a8-3737-43c2-86d3-9ac4d66f8f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8aac513d-61fc-4c76-9df1-60de0b433aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>89c114e3-def2-4770-955f-e105cbfabaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadPenelitianM-45</value>
      <webElementGuid>ce8349c4-d043-421e-8b86-03d53380a2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload
                                                        Lampiran</value>
      <webElementGuid>b017e0c1-f45b-4ded-9e91-7ebe8b88e92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadPenelitianM-45&quot;)</value>
      <webElementGuid>7fc67631-6817-40d6-b61e-12a709f32b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUploadPenelitianM-45']</value>
      <webElementGuid>7326d9ed-6d07-4b56-80d9-2999f3aad46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenelitian_M-45']/div/div/div[3]/button[2]</value>
      <webElementGuid>18470421-b489-4687-bbe8-582911bba7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[25]/following::button[1]</value>
      <webElementGuid>340134dc-c2dc-46c0-9bd3-52715c3b90a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mpdf.pdf'])[1]/following::button[2]</value>
      <webElementGuid>7a104498-d7c0-49be-97da-313eb525ddd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Jenis Dokumen yang harus dilengkapi :'])[26]/preceding::button[2]</value>
      <webElementGuid>b1f07b00-4031-4824-aa0a-e17d1f97d82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Permohonan sebagai Pembicara/Nara Sumber'])[2]/preceding::button[2]</value>
      <webElementGuid>f9786a1e-294a-4684-b234-d1527d5439b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/div[3]/button[2]</value>
      <webElementGuid>0d05a01a-2541-4e55-91f4-9cde52c988a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnUploadPenelitianM-45' and (text() = 'Upload
                                                        Lampiran' or . = 'Upload
                                                        Lampiran')]</value>
      <webElementGuid>a6948343-21f2-4fea-9fec-b67f12afb7c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
