<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files</name>
   <tag></tag>
   <elementGuidId>b99ae928-2a9f-4fec-8fc9-e2fd56dc12a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtnPenelitianK-41</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtnPenelitianK-41']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Files&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17eaa9cf-8d5b-4829-8cf1-f8c6a51e21dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6fbccf8-6a5a-4996-b707-62e578c73227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtnPenelitianK-41</value>
      <webElementGuid>656b60d1-b54f-4178-84ea-3edde72b38d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>32a11654-d6df-46ef-b861-7b4c274159fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>79b8408f-0361-4df3-bc5f-15a82ff85474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtnPenelitianK-41&quot;)</value>
      <webElementGuid>d8d7dc92-e58a-4032-8c4d-dbdaccd1ce1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtnPenelitianK-41']</value>
      <webElementGuid>1712948e-83f1-4968-bf6c-a15ee2a6730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenelitian_K-41']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>3dd95644-40ef-4b96-98b9-67f71a7492b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat'])[3]/following::button[1]</value>
      <webElementGuid>dab6383a-d8b2-499b-9632-bf412f5f68d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat Tugas Mengikuti Program Pekerti dari Pimpinan'])[5]/following::button[1]</value>
      <webElementGuid>f704c696-edfa-4ebf-9f1c-99684baa18b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[21]/preceding::button[1]</value>
      <webElementGuid>c127f9e9-05e4-4e71-8f43-ed91fda4ef1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>a86d2b12-de66-444f-9de4-2d46ae03a5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtnPenelitianK-41' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>6cb5169f-a50e-45e4-b84c-a06ee415c36e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
