<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mpdf_42_1435_Hak_Paten1716820756.pdf</name>
   <tag></tag>
   <elementGuidId>500c3b0b-654d-4697-9c79-30e30d9e8376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalEditPenelitian_K-42 > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.container > div.row > div.col-md-12 > div.mt-3.mb-3 > #existsFiles > div.file-item.d-flex.align-items-center.mb-2.border.rounded.p-3 > a.ms-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='existsFiles']/div/a)[50]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;mpdf_42_1435_Hak_Paten1716820756.pdf&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f202948-1b60-4c23-8f1e-44f8845c840a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>1ca9a4eb-16d0-405e-a89b-e45a00bfbf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpdf_42_1435_Hak_Paten1716820756.pdf</value>
      <webElementGuid>e6ebdd0a-81b8-4649-be2a-d527a897404c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditPenelitian_K-42&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>534a2944-e4f6-4f9f-806e-9d8ed20a4a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='existsFiles']/div/a)[50]</value>
      <webElementGuid>74d32743-be9c-4c4f-a36b-14a9172f3d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mpdf_42_1435_Hak_Paten1716820756.pdf')]</value>
      <webElementGuid>bce33c8d-485a-4e8d-8f26-d607de9f16d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[22]/following::a[1]</value>
      <webElementGuid>61ce7702-e600-45a4-9b63-2f2ece59110d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat'])[4]/following::a[1]</value>
      <webElementGuid>8c45e9b0-3239-42aa-b1da-010fddc1ba4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[22]/preceding::a[1]</value>
      <webElementGuid>2d857fa6-3fb3-490c-b496-da18558f3ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mpdf_42_1435_Hak_Paten1716820756.pdf']/parent::*</value>
      <webElementGuid>546eb8cb-b28a-41d7-b1cc-3b3176664eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>e213a692-baf5-4ce9-9ae4-a51aaeb9b029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'mpdf_42_1435_Hak_Paten1716820756.pdf' or . = 'mpdf_42_1435_Hak_Paten1716820756.pdf')]</value>
      <webElementGuid>11cc8699-d817-467e-85f9-a2279be49221</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
