<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yakin (4)</name>
   <tag></tag>
   <elementGuidId>e4275da5-8cf6-4836-af28-4a36e414ccc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirmDeleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b51be1d-a34a-41b6-9ca7-f4f8d3d7ed8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteBtn</value>
      <webElementGuid>4437dd72-a801-44bf-818a-214c46ee2626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>ac58ca0e-9b48-4fcb-8e49-5d4a9f846368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8000/formRencanaKerja/pendidikan/cangkok/9</value>
      <webElementGuid>903a7bf7-db20-495a-86e0-bb53cb323e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault(); document.getElementById('delete-form-9').submit()</value>
      <webElementGuid>48830785-b8e5-46db-855c-14e548383f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yakin</value>
      <webElementGuid>28d51ec7-0c5d-4bbc-9d46-ecc26a9d88d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDeleteConfirm-9&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer justify-content-center&quot;]/a[@id=&quot;confirmDeleteBtn&quot;]</value>
      <webElementGuid>5638521a-22a0-42d6-aed8-1f9e1eb7341a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirmDeleteBtn']</value>
      <webElementGuid>5b69033f-8ae9-4ce3-a1fb-d7c2d8aabbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDeleteConfirm-9']/div/div/div[3]/a</value>
      <webElementGuid>9de967e4-c7a4-469c-917a-25cf8dfd1243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Yakin')]</value>
      <webElementGuid>5c7f832a-bf9e-4711-aa66-67eb18000349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[1]/following::a[1]</value>
      <webElementGuid>79d203a0-8c00-4e80-afc7-8b8d0a5247d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[1]/following::a[1]</value>
      <webElementGuid>3ba0ffcb-8214-4787-a476-0b25e18971df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J. Koordinator Tugas Akhir/Skripsi, Proyek Akhir atau KP'])[1]/preceding::a[1]</value>
      <webElementGuid>c7c9beb0-472a-4d0c-a232-dc4a27d97cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Kegiatan'])[10]/preceding::a[1]</value>
      <webElementGuid>8758a44a-28cb-4c74-96b9-1753c3133a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yakin']/parent::*</value>
      <webElementGuid>6b3ee804-a774-487d-a8d7-57eec33b5d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8000/formRencanaKerja/pendidikan/cangkok/9']</value>
      <webElementGuid>a1d0acfc-16fb-4ee9-9aed-c7f3de813bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>809f1003-8608-4e7c-9327-435942865387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirmDeleteBtn' and @href = 'http://localhost:8000/formRencanaKerja/pendidikan/cangkok/9' and (text() = 'Yakin' or . = 'Yakin')]</value>
      <webElementGuid>6c9ad159-48ce-40fc-a8f5-10b9b3bff8bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
