<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yakin (21)</name>
   <tag></tag>
   <elementGuidId>95eb36cc-87ac-4ce7-bfee-6bd52775720d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirmDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8de826d1-6360-4be7-9414-3a177f386695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteBtn</value>
      <webElementGuid>11d9ea00-5bc4-4a10-83e0-687e9006ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>7c84bbd2-9059-4457-a473-f9c5b65a02ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/formRencanaKerja/penelitian/media_massa/20</value>
      <webElementGuid>bc25b7b5-c242-41c2-9be2-96c2f3007ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault(); document.getElementById('delete-form-20').submit()</value>
      <webElementGuid>ca01248d-95ae-4121-a8e0-3b89d39601b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yakin</value>
      <webElementGuid>c7663662-5a9b-412f-b214-2b219f48bd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDeleteConfirm-1&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer justify-content-center&quot;]/a[@id=&quot;confirmDeleteBtn&quot;]</value>
      <webElementGuid>721cbb80-cb7e-4df1-9537-1415f5157b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirmDeleteBtn']</value>
      <webElementGuid>10d09d13-8673-45bd-a87c-f5b4dbd1f000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDeleteConfirm-1']/div/div/div[3]/a</value>
      <webElementGuid>4987d159-febe-44b2-b123-d71b7f6f4558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Yakin')]</value>
      <webElementGuid>d3c61565-ec5c-4256-b1f9-bf116df5c315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/formRencanaKerja/penelitian/media_massa/20']</value>
      <webElementGuid>902b57fa-7138-4435-bfe1-d81972b2b650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>524cd6d3-e4e0-454d-82fc-23d750b47d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirmDeleteBtn' and @href = 'http://127.0.0.1:8000/formRencanaKerja/penelitian/media_massa/20' and (text() = 'Yakin' or . = 'Yakin')]</value>
      <webElementGuid>dcfca885-6574-432c-98d2-52e127855ac8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
