<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yakin (19)</name>
   <tag></tag>
   <elementGuidId>f05ff583-b0b9-4e8e-a713-a79d53e1506d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirmDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3209934d-839d-46e6-ac13-a5fd981384e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteBtn</value>
      <webElementGuid>a43f7ff2-ec87-49c3-8ee2-1c83a3fb727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>041af624-92d6-4760-bbb4-ee18971a2286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/formRencanaKerja/penelitian/jurnal_ilmiah/18</value>
      <webElementGuid>11020905-d403-4cbf-88c3-86875d7e2e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault(); document.getElementById('delete-form-18').submit()</value>
      <webElementGuid>47a2afd2-6282-4eeb-96e3-baa227b17dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yakin
                                                </value>
      <webElementGuid>1dcac708-87d6-48a1-89ce-e10ff0fef79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalDeleteConfirm-18&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer justify-content-center&quot;]/a[@id=&quot;confirmDeleteBtn&quot;]</value>
      <webElementGuid>155e5d55-81a3-43ab-94b1-e08a7cad114a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirmDeleteBtn']</value>
      <webElementGuid>91d14d3b-c6ad-4650-aabd-b6c4502463d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDeleteConfirm-18']/div/div/div[3]/a</value>
      <webElementGuid>e848099c-adc5-40fa-b6c3-8b1ea53ba46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Yakin')]</value>
      <webElementGuid>9521f298-af39-41a5-b0fa-064bb549488d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/formRencanaKerja/penelitian/jurnal_ilmiah/18']</value>
      <webElementGuid>126d1537-b90f-4998-98a4-5ca1cfaa2713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>a247625b-333f-4bdf-b9c3-807bb25cec16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirmDeleteBtn' and @href = 'http://127.0.0.1:8000/formRencanaKerja/penelitian/jurnal_ilmiah/18' and (text() = 'Yakin
                                                ' or . = 'Yakin
                                                ')]</value>
      <webElementGuid>df225bf0-22c2-436c-b3dc-7a07a308f991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
