<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yakin (6)</name>
   <tag></tag>
   <elementGuidId>4c436906-5936-40f3-9e59-44a51cc74eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirmDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8abb93fa-0ded-44a9-965d-3a3d12d19563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteBtn</value>
      <webElementGuid>587469eb-6766-43ae-9ed2-22e281960877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9077729d-3dc0-4cb4-9f9f-f0aedda56e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/formRencanaKerja/pengabdian/kegiatan/5</value>
      <webElementGuid>4f3cb1a8-c76b-45a3-b706-469b0f0490e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>event.preventDefault(); document.getElementById('delete-form-5').submit()</value>
      <webElementGuid>24608283-179b-4f2a-8e69-ded2a2aceee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yakin
                                                </value>
      <webElementGuid>2fcf953c-d597-4a47-8bd2-6005a515898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentPage&quot;)/div[@class=&quot;bg-abu container-fluid pt-4&quot;]/div[@class=&quot;mt-5 flex-wrap ml-4 mr-4&quot;]/div[@class=&quot;bg-white mt-2&quot;]/div[@class=&quot;card shadow-sm mt-5 ml-1 mr-1 bg-card&quot;]/div[@class=&quot;card-body&quot;]/table[@class=&quot;table table-striped table-bordered mt-2 text-center&quot;]/tbody[1]/tr[1]/td[7]/div[@id=&quot;modalDeleteConfirm-1&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer justify-content-center&quot;]/a[@id=&quot;confirmDeleteBtn&quot;]</value>
      <webElementGuid>92710b2a-2e04-4448-ae82-5c85b38d7515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirmDeleteBtn']</value>
      <webElementGuid>367e5f38-97f6-4137-93e3-67365a0fa8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDeleteConfirm-1']/div/div/div[3]/a</value>
      <webElementGuid>f0646b56-dbf4-431f-aef4-319a7daa4a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Yakin')]</value>
      <webElementGuid>fc4d45c1-44ae-4585-a035-5bc78721968b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/formRencanaKerja/pengabdian/kegiatan/5']</value>
      <webElementGuid>37f3e8a0-3db8-4df3-8581-793afd25d221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>fb601d51-b053-48ef-b73a-28ea04f13d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirmDeleteBtn' and @href = 'http://127.0.0.1:8000/formRencanaKerja/pengabdian/kegiatan/5' and (text() = 'Yakin
                                                ' or . = 'Yakin
                                                ')]</value>
      <webElementGuid>a05a593e-5916-489f-83ae-e39bb6332fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
