<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Menunggu_btn btn-warning mr-1 (21)</name>
   <tag></tag>
   <elementGuidId>c9b01785-83b3-4ddf-acad-e47ca5d6cf0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-B > tbody > tr > td:nth-of-type(7) > button.btn.btn-warning.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96922079-72d4-4769-9f29-49131c39f189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfd89c5f-9187-42d3-b0a4-64541ae902fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mr-1</value>
      <webElementGuid>ccaf1db0-4ae9-4d0c-8d9c-51ebd0b664b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>bde4a8fc-a3a7-4b42-9536-903c6fb4e059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEditPenunjang-2</value>
      <webElementGuid>20deb0ee-3719-4b26-b026-e2cfc8beca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-B&quot;)/tbody[1]/tr[1]/td[7]/button[@class=&quot;btn btn-warning mr-1&quot;]</value>
      <webElementGuid>7548dd9f-17b9-45c6-be25-590848d0de6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>e40cdea4-8cca-4cdd-a51d-8fe85a4d1d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-B']/tbody/tr/td[7]/button</value>
      <webElementGuid>83967148-5fe2-4f44-90fa-26d989f47289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[4]/following::button[1]</value>
      <webElementGuid>2944d1f4-1957-4d8a-88ba-679c27287127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[3]/following::button[1]</value>
      <webElementGuid>43f48398-574b-40b9-b92f-5c0cb1d8abb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Kegiatan'])[3]/preceding::button[2]</value>
      <webElementGuid>d0c30b51-9bf3-47b3-af2d-2c8ee2a60c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/table/tbody/tr/td[7]/button</value>
      <webElementGuid>9331fd68-b624-4588-9459-6af03563a486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>ff46673d-54df-47b6-90bd-e26068afac6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
