<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files (6)</name>
   <tag></tag>
   <elementGuidId>63b4bc52-7160-4626-87d6-569d9eaf9ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtn-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtn-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33300ac0-12e8-4f3e-a70c-f8b848d621ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>568a5ad4-b65a-4d96-848b-3063ce0f1486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtn-7</value>
      <webElementGuid>893c1109-be7c-4d63-bab9-508616fe0d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>318de152-6b07-4060-bf39-cfa930516541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>010419d0-6b3a-445e-aefa-e7d65c87c6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtn-7&quot;)</value>
      <webElementGuid>c76fc20e-2f5c-4c84-b9d1-a1dce4e87f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtn-7']</value>
      <webElementGuid>dc0119a9-4cfd-4af0-a11c-5ab60d87fb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditEvaluasiPenunjangG-7']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>9089d412-0d58-4010-a109-c8e277bfa52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>97d74dee-a87c-4ef9-888b-73fc02f5f420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtn-7' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>2d9ee97a-f550-4364-879a-fc1364176039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
