<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan (18)</name>
   <tag></tag>
   <elementGuidId>f2836987-b085-4f56-a5e4-ba329000bc59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-44']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ff2720f-0c61-4509-ab0c-4f8afeec0087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-44</value>
      <webElementGuid>5f081dd3-acea-4bad-b27b-1a871c04e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cda56fdc-948b-4af4-8916-3d95d5f6c560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>0dac5b48-9899-4865-838a-dd6a2ec1b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Simpan Perubahan
                                                    </value>
      <webElementGuid>3222eb39-5f88-45a8-8747-5ea9033b2f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-44&quot;)</value>
      <webElementGuid>12eaeb6f-8c0b-476a-82f1-61d93214d149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-44']</value>
      <webElementGuid>754454f3-53af-49a1-8769-5d2bec7941d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenunjang-44']/div/div/div[3]/button</value>
      <webElementGuid>da42e71a-dd30-4cd9-9c48-f22613aa7a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkatan:'])[1]/following::button[1]</value>
      <webElementGuid>a5e6939d-8840-42b9-8fd2-32f06444d6af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabatan:'])[1]/following::button[1]</value>
      <webElementGuid>b0b356bb-584e-4091-a55f-c41b0c51bdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[44]/preceding::button[2]</value>
      <webElementGuid>7b35bd15-9093-4107-a59d-5e79dbc7b8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[44]/preceding::button[2]</value>
      <webElementGuid>d9244fd1-a986-4f1b-a293-ccffd268421c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>17873f3f-4954-489c-8fab-39514cd7c7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-44' and @type = 'submit' and (text() = '
                                                        Simpan Perubahan
                                                    ' or . = '
                                                        Simpan Perubahan
                                                    ')]</value>
      <webElementGuid>275b6822-f2f7-4e9c-9a00-e13b45d8c2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
