<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files (1)</name>
   <tag></tag>
   <elementGuidId>cd95de81-517a-4842-a0b5-99a777757b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtnPengabdianB-51']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtnPengabdianB-51</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b21e1bf4-7510-405c-8c5c-0be37d117ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5701769-a37e-43fd-abe3-9b9702e2787a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtnPengabdianB-51</value>
      <webElementGuid>1c6725f0-5f46-4af5-bee0-4034145ad3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>64786302-9457-4621-8eb5-830a4334a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>e0125f21-3e50-4f85-8bf0-c5389f921de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtnPengabdianB-51&quot;)</value>
      <webElementGuid>0a782fee-b3bd-48b1-9a06-4a0eacba2092</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtnPengabdianB-51']</value>
      <webElementGuid>e41a2719-b972-4f7a-b566-57d7ae509100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditEvaluasiPengabdian_B_51']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>d8c9f81c-43d1-407e-9d0b-04ccbc80a601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materi yang disampaikan'])[2]/following::button[1]</value>
      <webElementGuid>e75384e4-55cd-44c1-b7a2-a6284b733a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan kegiatan'])[2]/following::button[1]</value>
      <webElementGuid>d3a650fc-0954-4e0b-924e-624f709b6cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAS_51_1435_penyuluhan1716542761.pdf'])[1]/preceding::button[1]</value>
      <webElementGuid>4de21d46-8a5a-4c9c-a5c4-5420ebc67e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[2]/preceding::button[1]</value>
      <webElementGuid>0e325543-f5a9-4fc7-9904-5808a880c75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>d7f44e2d-20c6-488d-860f-d24d232cc065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtnPengabdianB-51' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>80dd96e2-4c0a-41b5-920b-acdb82720d15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
