<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files (1)</name>
   <tag></tag>
   <elementGuidId>6d1a0d98-def3-4e8e-8597-f3217e9bb0ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtn-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtn-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89ff931f-71b1-426a-9c74-7766dbb5ce11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f8584d0-8021-472b-b6be-989ae21db4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtn-2</value>
      <webElementGuid>aa57c66c-d2ab-47b4-89fd-439aada79f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>135a727a-c47e-4e0a-91d0-25aad391d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Add Files
                                                        </value>
      <webElementGuid>9297b8f6-445d-4311-9793-0f1c59a449b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtn-2&quot;)</value>
      <webElementGuid>86c46eb0-70e0-4637-9ae0-a8f3f46b9561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtn-2']</value>
      <webElementGuid>55d137d2-d51d-43df-9eec-37d575d829ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditEvaluasiPenunjangB-2']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>173bada4-18d8-4709-8231-03597b5489ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>150b38af-a6c2-4dd6-b4dd-cb072a0e42af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtn-2' and (text() = '
                                                            Add Files
                                                        ' or . = '
                                                            Add Files
                                                        ')]</value>
      <webElementGuid>83af18a9-de17-4e4c-ab8d-0b3e39afcf33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
