<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan (1)</name>
   <tag></tag>
   <elementGuidId>3ebfae4e-bbd0-4423-b773-e3eeb422f587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4986a905-0464-45b6-8c9a-e11841e04ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-2</value>
      <webElementGuid>9b2f1d6e-2d5e-4cf2-bc33-223badbe97cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>29768af9-ea47-44ea-947a-544d5a863f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>092fb2c0-9f39-418e-907c-ee9fbbfde85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Simpan Perubahan
                                                    </value>
      <webElementGuid>c0228bcf-7b0b-48a4-b36b-ef36983469ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-2&quot;)</value>
      <webElementGuid>9c48a460-6939-4415-a99f-c5d47a3acbf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-2']</value>
      <webElementGuid>5353b970-1df3-4c27-bbe3-769bd8b5bdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan-2']/div/div/div[3]/button</value>
      <webElementGuid>4e2feeb8-1a20-4f6d-a1dc-7fe61d7c7d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKS Praktikum (1 SKS = 2 jam)'])[1]/following::button[1]</value>
      <webElementGuid>d567e5d7-e39a-4306-bbb6-3b6b2b333021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Kelas'])[1]/following::button[1]</value>
      <webElementGuid>4d9d2628-5b1e-4b4a-aceb-43343e3012e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[2]/preceding::button[2]</value>
      <webElementGuid>dd74b122-fefd-4f4b-ad71-d3fadf8d77a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[2]/preceding::button[2]</value>
      <webElementGuid>25c770c9-1ce8-46a1-b71e-eb38b974fdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>33f9694d-53c2-4668-a459-086c3075b04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-2' and @type = 'submit' and (text() = '
                                                        Simpan Perubahan
                                                    ' or . = '
                                                        Simpan Perubahan
                                                    ')]</value>
      <webElementGuid>c457ddb5-6a8a-4ad2-b5b1-bc1b4f295be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
