<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Menunggu_btn btn-warning mr-1 (16)</name>
   <tag></tag>
   <elementGuidId>bad38396-1bcd-49a3-9618-6d7239b59158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[256]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-M > tbody > tr > td:nth-of-type(7) > button.btn.btn-warning.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7368272a-cae2-40db-a080-c482a637335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fbe1d44-4bcd-4130-a313-798b1a98f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mr-1</value>
      <webElementGuid>f38eadf0-5e11-47b4-892d-b7197e50e576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>21701f54-1912-45c0-ab1f-917c6343aa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEditPenunjang-48</value>
      <webElementGuid>f6f9254a-6c23-49bd-a0f2-7ddec1d46eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-M&quot;)/tbody[1]/tr[1]/td[7]/button[@class=&quot;btn btn-warning mr-1&quot;]</value>
      <webElementGuid>ac2fc5ad-7ae6-4595-b89b-d79f833ce360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[256]</value>
      <webElementGuid>362559de-6e86-483b-b878-ebab9e065384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-M']/tbody/tr/td[7]/button</value>
      <webElementGuid>d1dbd946-4593-4e80-8d4d-ef7849535669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[96]/following::button[1]</value>
      <webElementGuid>43f5f5f5-1bec-4ea0-b800-7dfed064209e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[95]/following::button[1]</value>
      <webElementGuid>19fe5c62-abce-466b-ab8b-6da9172997d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workshop'])[1]/preceding::button[2]</value>
      <webElementGuid>ac487855-65e6-4d97-ab86-176776e9cf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internasional'])[10]/preceding::button[2]</value>
      <webElementGuid>1bdf181e-71dc-4cf3-845b-2e94e3e28468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/table/tbody/tr/td[7]/button</value>
      <webElementGuid>6f51198e-2c3c-4a03-b226-7efbe813c9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>2dfc2b9a-87d2-4390-a5a2-ff934195d52e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
