<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Menunggu_buttonEdit-2 (1)</name>
   <tag></tag>
   <elementGuidId>1d31b2ee-8d6d-4c00-bcca-c247af108a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonEdit-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEdit-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d2c233a-3120-4b21-ac59-6bcbf4496d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonEdit-2</value>
      <webElementGuid>bc35e522-84e7-499f-9f77-2ab27e04778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f43e6f2e-2ce3-4fd0-ac5a-b67b7fbd2eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mr-1</value>
      <webElementGuid>01f7a2a5-9e8d-47df-93f6-a6b3e78a9efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3643a184-983a-4305-bb85-1a629d2770ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEditPendidikan-2</value>
      <webElementGuid>f72a42d7-b8ce-4e88-9018-2ca8100492b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEdit-2&quot;)</value>
      <webElementGuid>09a31b7a-a4c1-4c55-9ab5-24e7049a941d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonEdit-2']</value>
      <webElementGuid>6ddd5270-6b1e-426e-b24f-b2d7b4fba4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-B']/tbody/tr/td[8]/button</value>
      <webElementGuid>62c36d6f-bc31-455d-b4cc-294438bd6455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[4]/following::button[1]</value>
      <webElementGuid>d141c46d-503c-446d-bb67-b7b52d1c0733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[3]/following::button[1]</value>
      <webElementGuid>bd7eeff2-f775-4523-8bab-08eea406211e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Kegiatan'])[3]/preceding::button[2]</value>
      <webElementGuid>bda28466-9b73-4fad-8c61-cab3809a4262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button</value>
      <webElementGuid>3d4da037-317c-4a94-80b5-6f746800eb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonEdit-2' and @type = 'button']</value>
      <webElementGuid>cd811038-c78b-4686-b2e3-d8d5c3e63002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
