<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan Perubahan (20)</name>
   <tag></tag>
   <elementGuidId>825f6a4c-2d10-4a75-8109-44342ecf4e9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-50']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d853e41d-13ba-453e-ad77-8e43b2ba3505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-50</value>
      <webElementGuid>e48a398b-74f8-4a04-bcb9-bfe9f5243e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fb171e34-d0b4-4167-8511-e93bdafc5e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>889fb2ca-9c06-4203-a99f-9448b92cdd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Simpan Perubahan
                                                    </value>
      <webElementGuid>242b5b4e-3e0d-434b-9c1f-a3214b1922e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-50&quot;)</value>
      <webElementGuid>e4a1a127-fffa-4d0a-a37f-07d0ad91f229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-50']</value>
      <webElementGuid>2d84be3c-a939-418b-8daa-2dd606969295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenunjang-50']/div/div/div[3]/button</value>
      <webElementGuid>b58880b1-4205-47d1-b806-8adbc38424d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kegiatan:'])[7]/following::button[1]</value>
      <webElementGuid>c13f6f57-e762-4d8b-aa05-11eecab88dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Kegiatan'])[14]/following::button[2]</value>
      <webElementGuid>9681de63-aeeb-4eb4-b5dc-37fd4d1cfbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[50]/preceding::button[2]</value>
      <webElementGuid>89ac64f4-d440-457c-b3c4-a4052ba352d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[50]/preceding::button[2]</value>
      <webElementGuid>86e71cfa-9f15-44ee-b74f-a23da3cb9528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>cc4a6821-4939-4e36-91b8-c806e7897dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-50' and @type = 'submit' and (text() = '
                                                        Simpan Perubahan
                                                    ' or . = '
                                                        Simpan Perubahan
                                                    ')]</value>
      <webElementGuid>2e7da193-95d0-469b-99c0-18675a7acc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
