<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files (2)</name>
   <tag></tag>
   <elementGuidId>f0a1722c-a4f7-4408-977d-ec8a768914a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtnPengabdianB-51']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtnPengabdianB-51</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcc0fb92-5a3b-4af2-80b7-35374dd507b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75c03a89-a6a5-4de8-acb8-0f7bd5110ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtnPengabdianB-51</value>
      <webElementGuid>117bf6c4-3f84-47ed-8124-75801a943521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>2fefbb8b-92dd-4d40-8b56-ea265511aa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>efc8b640-b1e9-489c-90ce-81cb032a29bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtnPengabdianB-51&quot;)</value>
      <webElementGuid>41ad9444-acfb-4c83-aed1-455f01640178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtnPengabdianB-51']</value>
      <webElementGuid>808f17e2-ef56-49de-acca-d5b6469824c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditEvaluasiPengabdian_B_51']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>f27a588c-82dd-474b-86db-4f96092b46c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Materi yang disampaikan'])[2]/following::button[1]</value>
      <webElementGuid>27e3e657-1260-429e-99b6-6b1eb68fd6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan kegiatan'])[2]/following::button[1]</value>
      <webElementGuid>c8920aa1-17d7-4c87-8c2b-62f88f63cdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAS_51_1435_penyuluhan1716542761.pdf'])[1]/preceding::button[1]</value>
      <webElementGuid>0c9479be-b293-4e2f-b694-512e0bded4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surat IB_51_1435_penyuluhan1716803589.pdf'])[1]/preceding::button[1]</value>
      <webElementGuid>a28be29b-c33e-434d-b843-758393320704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>bd380f78-6291-433f-b634-1d0c8218b3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtnPengabdianB-51' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>8e0e5d4c-f40a-42e3-9dca-3ab99d59833c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
