<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan (65)</name>
   <tag></tag>
   <elementGuidId>b25c8e8a-3588-4413-998e-6bba4e8b30d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='penunjang_simpan_N']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#penunjang_simpan_N</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a63d6ef9-75cc-4ee6-b22b-cbda5727fa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjang_simpan_N</value>
      <webElementGuid>96007233-bb3c-4093-a415-ca57e89e88e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>922e097b-296a-48af-8f2e-3a4be0325515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>c0e1476c-feba-4d20-bd78-4c1e2b928cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>077ac2cc-9972-4dde-8ba5-c38ebd8208f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjang_simpan_N&quot;)</value>
      <webElementGuid>e041253a-4d13-439e-b802-e86b03c3c302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='penunjang_simpan_N']</value>
      <webElementGuid>032ca003-a856-432f-b43b-90d0aa510ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_N']/div/div/div[2]/form/div[2]/button</value>
      <webElementGuid>4331f323-2e1c-43b7-8457-696a3510e2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kegiatan:'])[14]/following::button[1]</value>
      <webElementGuid>3e0819ca-8760-434b-bd89-942600ceec68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N. Reviewer Jurnal Ilmiah , Proposal Hibah dll'])[1]/following::button[2]</value>
      <webElementGuid>4e15d726-eefe-4c05-ac6c-b60dfdd0baca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div/div/div[2]/form/div[2]/button</value>
      <webElementGuid>ba0b55ec-543b-493c-a6ea-2e63077b181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'penunjang_simpan_N' and @type = 'submit' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>767505c0-ed25-4909-9501-1f5828a4ca0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
