<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Kegiatan (34)</name>
   <tag></tag>
   <elementGuidId>c2ba5ff2-3498-44fa-947a-47bc9f265169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenelitianH']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenelitianH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72800a3b-8ba0-456b-9555-e6624ebbe1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenelitianH</value>
      <webElementGuid>ebb47db1-4f07-4160-9cc7-6fe59d10eae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46689d7b-d06a-419f-81cc-26f78dd896f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto m-1</value>
      <webElementGuid>1a815b98-599e-4f4b-9ec0-48506183f743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f2a06bf5-dfd5-4a22-ab0a-4fd1bf077d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalPendidikan_H</value>
      <webElementGuid>30fcda5a-9791-426a-947c-f58dd4adbd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Tambah Kegiatan
                </value>
      <webElementGuid>62e68624-c829-42c3-920a-c05c57958e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenelitianH&quot;)</value>
      <webElementGuid>ac0f9100-4834-4205-b0ae-c3fd1297b335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianH']</value>
      <webElementGuid>61a652a5-3f98-4342-8140-3b07e723017e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pendidikan-H']/div/div/button</value>
      <webElementGuid>3210a72e-11d9-40a8-85be-f57e1a2ad527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[7]/following::button[1]</value>
      <webElementGuid>88bfb1b6-4ba5-42b0-8787-16d244430f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 1'])[7]/following::button[1]</value>
      <webElementGuid>f2f2f1de-3bf7-48da-8d00-759aec5e4cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[8]/preceding::button[1]</value>
      <webElementGuid>94236540-928d-43a2-91c2-da3e623a4e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[8]/preceding::button[1]</value>
      <webElementGuid>d50d3fc1-d0e8-4e0a-b9f4-45dac3136ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/button</value>
      <webElementGuid>78f3c9f1-13d1-417f-8ee8-2accdbad4fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianH' and @type = 'button' and (text() = '
                    Tambah Kegiatan
                ' or . = '
                    Tambah Kegiatan
                ')]</value>
      <webElementGuid>c00d7005-34f3-4f23-addb-9b3bf419b03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
