<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yakin (4)</name>
   <tag></tag>
   <elementGuidId>04f2cf89-e397-4321-931b-fac611004431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmDeleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmDeleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47f0d723-44c8-44a8-82cc-558b1bfc80f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmDeleteBtn</value>
      <webElementGuid>334258a2-90d8-4345-965e-cab75a816d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5d61d39c-cefe-4db2-be91-854554b7c713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>3005d9bd-c102-4f8b-9937-f6ab2e0f64a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yakin</value>
      <webElementGuid>81de5b71-114b-43ad-9173-42f8fe6afd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmDeleteBtn&quot;)</value>
      <webElementGuid>96ba9b42-3a56-4538-9432-57befbad2e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmDeleteBtn']</value>
      <webElementGuid>4771c6ab-8142-46ba-a7cf-027775d21a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSubmitConfirm']/div/div/form/div/button[2]</value>
      <webElementGuid>f923c821-b3a3-4ea1-8fe9-9a9ac9253cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[1]/following::button[1]</value>
      <webElementGuid>24e4c10e-9fcc-4484-9d78-656a7e4a60c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menyimpan permanen kegiatan ini?'])[1]/following::button[2]</value>
      <webElementGuid>862cfa89-08d1-4723-8226-9fb1984d3b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yakin']/parent::*</value>
      <webElementGuid>bb45d7bd-e48f-4bbc-b0c7-958459d59cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>da6ff9f5-26fe-49b1-8712-35041e6d3dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'confirmDeleteBtn' and @type = 'submit' and (text() = 'Yakin' or . = 'Yakin')]</value>
      <webElementGuid>287b44db-060f-44a6-b4fe-039286b141fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
