<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah                    Kegiatan</name>
   <tag></tag>
   <elementGuidId>5be903d0-e061-4d40-aed9-bc0ef050ae40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenelitianD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenelitianD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb529df9-dba8-4dbf-8642-67c2a3bfac84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenelitianD</value>
      <webElementGuid>96a79c22-a4b3-41ce-a1a8-26472bb1c3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28cee55d-7ead-4c53-b1ca-77908a9eb7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto mt-2 mb-2</value>
      <webElementGuid>690f822e-99cb-4dee-b9a2-0741eea8c3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>1794b41a-c6de-4c73-bb3e-ea92b14f3e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalpengabdian_D</value>
      <webElementGuid>2b5b0702-2364-454a-aa1a-3327fb8cc387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah
                    Kegiatan
                </value>
      <webElementGuid>8bd708f4-3da7-43e3-8a0f-cb27d2083774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenelitianD&quot;)</value>
      <webElementGuid>73a1cf24-5329-4063-ab14-2afc2412035f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianD']</value>
      <webElementGuid>d888f510-4373-41bf-982a-7cb24e14e249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[10]/div/div/button</value>
      <webElementGuid>187f8246-c885-4cab-aaf4-dcdbeb190261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/button</value>
      <webElementGuid>066f404f-5bbf-4004-8467-2e47be9ac544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianD' and @type = 'button' and (text() = 'Tambah
                    Kegiatan
                ' or . = 'Tambah
                    Kegiatan
                ')]</value>
      <webElementGuid>5a1b201f-cca2-4f3d-bf32-eadef267b9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianC']</value>
      <webElementGuid>cb24b1d7-96d9-45f5-b6eb-815cb3455bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[8]/div/div/button</value>
      <webElementGuid>2287885e-c7cd-4738-8824-5b54fe0ecf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/button</value>
      <webElementGuid>dfc71861-12ad-44d6-90bf-2b03a6dbb2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianC' and @type = 'button' and (text() = 'Tambah
                    Kegiatan
                ' or . = 'Tambah
                    Kegiatan
                ')]</value>
      <webElementGuid>8bfe4d63-be91-4a66-895e-67b521d9deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianB']</value>
      <webElementGuid>088b32fe-c5c4-49cd-ae15-a990599f33ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[6]/div/div/button</value>
      <webElementGuid>603400f0-c07b-4b87-a181-e3b71115638a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>1fae1638-d87e-4448-8728-229dc8b826fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianB' and @type = 'button' and (text() = 'Tambah
                    Kegiatan
                ' or . = 'Tambah
                    Kegiatan
                ')]</value>
      <webElementGuid>f1ac54e8-3eeb-443f-a911-bb0ad7c0c18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianA']</value>
      <webElementGuid>7cf0abf7-b893-47dc-9b89-bb1a4d1baf44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[4]/div/div/button</value>
      <webElementGuid>7dff97dd-f071-4792-ac0c-a04ee11ee8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>fe48519b-7c7f-40e1-92ea-09e416c6cf2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianA' and @type = 'button' and (text() = 'Tambah
                    Kegiatan
                ' or . = 'Tambah
                    Kegiatan
                ')]</value>
      <webElementGuid>81fe3a86-872b-41bc-8cc0-3904741fcae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
