<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Kegiatan (102)</name>
   <tag></tag>
   <elementGuidId>a439964d-8a28-4aeb-9188-f78b8a0471c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenelitianG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenelitianG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a152b38-de8c-4f79-85a3-fbfcdbab88cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenelitianG</value>
      <webElementGuid>f6ec52dd-1bc4-4128-86d5-a6fdf70d81a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d430013-084d-4c18-aeb4-6a317383b05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto mt-2 mb-2 </value>
      <webElementGuid>c441fd7d-3cbd-45fa-bf10-f63617ec72d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4fa82ac9-31cf-4d12-b946-9af6486ba82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalPenelitian_G</value>
      <webElementGuid>71e06be9-bf19-43ec-960d-29cfde99835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Kegiatan</value>
      <webElementGuid>dd6c0f96-07e4-4589-ac44-20c9e4c8445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenelitianG&quot;)</value>
      <webElementGuid>4b91d362-a63c-4b87-8060-44d0f165e91b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianG']</value>
      <webElementGuid>9b029cc9-6368-4b9a-842d-4a4c5c600a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[10]/div/div/button</value>
      <webElementGuid>5225b616-e03d-4dfe-bd5b-89e00b54a46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin'])[2]/following::button[1]</value>
      <webElementGuid>ee824b12-13c0-4877-9783-d2d764ed710b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[2]/following::button[1]</value>
      <webElementGuid>12d81405-5065-462f-aa3d-d0cef514fdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/button</value>
      <webElementGuid>c5657e81-5c0d-4aeb-9c6a-400b845c9f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianG' and @type = 'button' and (text() = 'Tambah Kegiatan' or . = 'Tambah Kegiatan')]</value>
      <webElementGuid>bc3261ff-130a-4412-9957-aa345106f941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
