<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Kegiatan (3)</name>
   <tag></tag>
   <elementGuidId>ad3d2a9e-30e8-4674-bac0-10d2f7dcc66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenelitianD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenelitianD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>452b0f01-0a14-41cc-846f-e55e9a8c955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenelitianD</value>
      <webElementGuid>da99e13c-ff3c-4906-8a07-caf4826903ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a20266c0-a61e-4a79-801c-9f477e8f4f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto m-1</value>
      <webElementGuid>d28089e3-adcd-443f-af6c-b724ad3c0d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>dfe99891-e67f-4991-8563-d87521829696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalPendidikan_D</value>
      <webElementGuid>821969bc-30ce-4b4a-ace3-12fb3ecf288e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Tambah Kegiatan
                </value>
      <webElementGuid>430f9ce3-fd30-4d52-8a38-86743afc4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenelitianD&quot;)</value>
      <webElementGuid>29bbcabb-1261-4303-b297-84a233255068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianD']</value>
      <webElementGuid>405252e1-f2d0-4b83-8f9d-a7d6c10b7cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pendidikan-D']/div/div/button</value>
      <webElementGuid>cdda821e-a39c-4616-9cc0-35a03311f1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D. Seminar yang terjadwal terhadap setiap kelompok'])[1]/following::button[1]</value>
      <webElementGuid>5b0a2e76-9b24-4235-99fc-c02ce7d11769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin'])[3]/following::button[1]</value>
      <webElementGuid>a64fc982-2b4d-4f82-b933-a737e983102f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[4]/preceding::button[1]</value>
      <webElementGuid>672ac100-612b-456f-8aaf-24b249ed9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[4]/preceding::button[1]</value>
      <webElementGuid>a62df250-6fbc-4a92-a5f8-ba915d5b4b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/button</value>
      <webElementGuid>852cbc4c-43c8-43a1-ad0f-ac5306fbddfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianD' and @type = 'button' and (text() = '
                    Tambah Kegiatan
                ' or . = '
                    Tambah Kegiatan
                ')]</value>
      <webElementGuid>c5ddc4be-4096-4ff5-b728-213c9bb0e82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
