<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Kegiatan (50)</name>
   <tag></tag>
   <elementGuidId>761924c5-61da-4007-91e7-e63d0c047e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenunjangH']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenunjangH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a989093-b40b-41bd-8ec0-1a96fb06dc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenunjangH</value>
      <webElementGuid>fce80493-9107-4535-af43-aa03b88c3d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a4feb8b-bf23-4aec-a511-a1ff1167a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto m-1</value>
      <webElementGuid>cbe0a246-bdda-459d-aee4-94fd17072857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5dab0d8f-932e-4157-8083-55da8f56bef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalPenunjang_H</value>
      <webElementGuid>d30d61bf-f2f6-4010-8fdb-874dd3eff352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Tambah Kegiatan
                </value>
      <webElementGuid>5b8d273a-96f8-431c-9fbd-48c3a54f471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenunjangH&quot;)</value>
      <webElementGuid>9e6330e5-0105-4aff-9fb5-0e8b1d03984e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenunjangH']</value>
      <webElementGuid>d2ce3871-680c-4adb-b86b-273c895d9dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='penunjang-H']/div/div/button</value>
      <webElementGuid>d40faf19-5854-4013-8a83-c26bdd39a801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin'])[33]/following::button[1]</value>
      <webElementGuid>0c1764b0-d7af-4bf8-bf4a-bdfca281eeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[33]/following::button[1]</value>
      <webElementGuid>41e75224-e70c-4f0b-8151-90a669d2c695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[8]/preceding::button[1]</value>
      <webElementGuid>3b4be364-b6e6-4b2e-8cc5-e41d9cb7d3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[8]/preceding::button[1]</value>
      <webElementGuid>3eaf06bd-ff5d-4947-a13c-65be14379b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/button</value>
      <webElementGuid>4f1b6abf-b600-4c87-a83e-04843cb01c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenunjangH' and @type = 'button' and (text() = '
                    Tambah Kegiatan
                ' or . = '
                    Tambah Kegiatan
                ')]</value>
      <webElementGuid>1ee952a2-84aa-485e-9205-251562de15dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
