<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Kegiatan (116)</name>
   <tag></tag>
   <elementGuidId>94665425-790a-4415-824d-9af76386541d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFrkPenelitianC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFrkPenelitianC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53041a66-35b3-4a1a-928d-a8dbad0c348e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFrkPenelitianC</value>
      <webElementGuid>97d453fb-ed9a-40a1-b6bd-82e6c89535fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f98ada9-0c51-42b7-a753-147422b7a015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success col-md-auto mt-2 mb-2</value>
      <webElementGuid>b5928394-8d5c-4b95-b402-fae48bdbedaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d649c232-ad26-4327-b28b-1e8aaa0205b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalPenelitian_C</value>
      <webElementGuid>8fcfc980-6a02-4f9c-b122-1b29b3f2e8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Tambah Kegiatan
                </value>
      <webElementGuid>0214c887-9c4b-4482-911c-3fc8ba7f1ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFrkPenelitianC&quot;)</value>
      <webElementGuid>4fa06519-69cd-44ff-8246-fee322ed9369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFrkPenelitianC']</value>
      <webElementGuid>ac3ecd83-8d67-4bc5-9e20-ea02c2587655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='contentPage']/div/div/div[2]/div[6]/div/div/button</value>
      <webElementGuid>4bc009df-38f4-4047-b72d-ea3af51bea73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[2]/following::button[1]</value>
      <webElementGuid>7ce2dd7a-0d84-46d1-a9a3-824207fc06cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 1'])[2]/following::button[1]</value>
      <webElementGuid>910969a7-8051-49fa-94f3-2ac6dcba922b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[3]/preceding::button[1]</value>
      <webElementGuid>b11db754-fa9f-41b2-9861-4486dbe3ee09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[3]/preceding::button[1]</value>
      <webElementGuid>afed3843-508b-4e6f-a594-dcbe341f4ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>a4360aa6-0309-4db3-b5c9-400b6991c944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnFrkPenelitianC' and @type = 'button' and (text() = '
                    Tambah Kegiatan
                ' or . = '
                    Tambah Kegiatan
                ')]</value>
      <webElementGuid>654ac87f-ff5b-4ded-9c94-fee235a2d631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
