<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Menunggu_bi bi-pencil-square (10)</name>
   <tag></tag>
   <elementGuidId>5414a877-bc48-46c6-a170-70bbe9bdf311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonEdit-6']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEdit-6 > i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0c6acca8-eaf1-4903-b50b-86bbbe9ccba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>5441853a-5ec1-4f89-a826-a6fdaec05d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEdit-6&quot;)/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>76a94113-b711-4e00-965a-b6dd5d125c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='buttonEdit-6']/i</value>
      <webElementGuid>d3f4559d-427d-4317-b74d-e35168596c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/table/tbody/tr/td[7]/button/i</value>
      <webElementGuid>ee051e81-15af-4ee4-b5a3-eb9a2cf0a8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
