<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Menunggu_bi bi-pencil-square (20)</name>
   <tag></tag>
   <elementGuidId>093ba96c-7e8d-4dab-a825-ce580d81fbd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonEdit-17']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEdit-17 > i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>61fe9cd7-f838-4578-8e4d-69a95402b821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>0a4b7451-6492-44fb-82c0-18d1c220557e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEdit-17&quot;)/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>93214fbd-ca07-477a-8306-7e0357fd9262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='buttonEdit-17']/i</value>
      <webElementGuid>1f7bdc84-1933-409c-b9b5-a7b655baa636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/table/tbody/tr/td[7]/button/i</value>
      <webElementGuid>925a6fcc-b62c-48ab-aef7-c3de74b724bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
