<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Menunggu_bi bi-pencil-square (15)</name>
   <tag></tag>
   <elementGuidId>ed1d6cc8-0971-4519-b665-a1a74ba316d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonEdit-2']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEdit-2 > i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5a8c8095-79ca-44c2-b25e-349cfb8da0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>72d045b1-a1b3-4d01-87da-4434730e4aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEdit-2&quot;)/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>e06de2c3-2812-499b-b00a-a96575a4e936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='buttonEdit-2']/i</value>
      <webElementGuid>fa12b20c-249c-44ca-ae3e-410a9c382495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button/i</value>
      <webElementGuid>e9c229d9-12ad-4146-8d42-800149c0c77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
