<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Menunggu_bi bi-pencil-square (8)</name>
   <tag></tag>
   <elementGuidId>aea1128b-6bfb-4cd9-b5f4-a2390aed5d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonEdit-5']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEdit-5 > i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>80181987-5624-4d92-afd9-1058ca200468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>9be74c02-a1a4-4b3d-9945-086a9e78887e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEdit-5&quot;)/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>7385ce7b-ba3d-432a-91c8-a34019c34847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='buttonEdit-5']/i</value>
      <webElementGuid>3dfcd227-9bba-4de1-b598-61b386905064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/table/tbody/tr/td[7]/button/i</value>
      <webElementGuid>d39cd4ed-afc5-4cda-b5c0-28e89ead74e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
