<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Anggota_jumlah_anggota (2)</name>
   <tag></tag>
   <elementGuidId>129732e2-00db-422f-b83f-1314cc4c9679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div/div/div[2]/div[18]/div/div/form/div[1]/div[4]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jumlah_pene_A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5bf0512-0e1b-48a4-83ab-74c77e8f0a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumlah_pene_A</value>
      <webElementGuid>6f4f5ad2-90c5-408f-b0b9-cef907c52bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_anggota</value>
      <webElementGuid>dc52cdf5-cd99-4bf6-855b-e8fbf8e96f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9fd2ecd2-4f4e-4bb9-b903-6f61deb1ab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>54e302a5-0f8a-4da1-bde2-ea8976f453ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8eb09781-49cf-435d-906a-1d14a8684933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id3</value>
      <webElementGuid>3a6043d2-1173-486a-9c08-2e9553dec94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumlah_pene_A&quot;)</value>
      <webElementGuid>87089ebe-dc77-4641-9cef-5a93afbf7de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jumlah_pene_A']</value>
      <webElementGuid>2849388f-373a-4385-aaf8-9acdab7bf59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenelitian_A']/div/div/form/div/div[4]/input</value>
      <webElementGuid>4ffdbf56-258c-4676-ad4c-240fff844356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b06bf969-8469-43d9-9f70-418a820cd9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jumlah_pene_A' and @name = 'jumlah_anggota' and @type = 'number']</value>
      <webElementGuid>badcb8ff-8af9-4d6f-80ad-a3fd8e56ab2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
