<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (6)</name>
   <tag></tag>
   <elementGuidId>aa2046bc-b672-4d6d-99f7-ba1c17e56c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_nama_kegitan_C</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_nama_kegitan_C']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08d9d38f-539f-4ce6-84dd-dbcc1fb26f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_nama_kegitan_C</value>
      <webElementGuid>5cd2c529-cc1a-46fe-b0a8-4ac2c8969ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51096f5e-0075-4e03-b9ea-9b8df0313ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>50d20b04-ecab-4009-8287-69fcaabc86e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>90139d40-52d8-4ac9-9e0c-f5508b84dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_nama_kegitan_C&quot;)</value>
      <webElementGuid>2c32deb2-ca34-4f2a-9a40-53af80543b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_nama_kegitan_C']</value>
      <webElementGuid>4b0e4836-29b1-4577-b3c6-6d2d42710ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_C']/div/div/form/div/div/input</value>
      <webElementGuid>27daaca4-3b99-4be3-8477-88e3fc4108c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/form/div/div/input</value>
      <webElementGuid>96eb8a3d-a72e-4622-88eb-5605e105c53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_nama_kegitan_C' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>78dadd55-7c09-41f8-bfc4-77dbc3d2e226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
