<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama                                 _c3a99b (25)</name>
   <tag></tag>
   <elementGuidId>85eaf6b7-feda-4e59-87ad-9717d0d0e964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac1085d5-4a99-4678-9ae2-ebad6c98f455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-2</value>
      <webElementGuid>7ddce650-a779-4ab2-8739-2a0a512fc1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test Pendidikan A 2</value>
      <webElementGuid>00813cd6-8201-4318-870b-edafda6fe582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b33ffbfc-2f2f-4421-92d6-d7a7ec7c5ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0f607725-252e-4177-92bf-1a74054c737d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>021c3649-1052-443a-94cc-715ceaeeee41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-2&quot;)</value>
      <webElementGuid>e3eea985-3a79-44ec-9439-bbf60034a699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-2']</value>
      <webElementGuid>ccfa5e31-58dd-4fe5-b7e8-7138a3dceebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan-2']/div/div/div[2]/div/input</value>
      <webElementGuid>01e1512d-66d5-4414-8017-d66adcf04dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6a65df4a-294a-4c92-88b7-b0d9116daf40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama-2' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>7ce34150-7e7e-420b-ae20-a5288ec5ec5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
