<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama                                 _42d808 (3)</name>
   <tag></tag>
   <elementGuidId>7c84f147-73f0-4235-8cf4-5f03763b67f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama-34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b5e65f-67c3-465f-b6e4-5cbc17424b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-34</value>
      <webElementGuid>8087d38a-6ce6-4a49-b73b-f63f1ef8082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Perencanaan Strategis</value>
      <webElementGuid>bca137e1-7ae3-40d7-a335-6fbd7978d322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a572334d-a1a7-4b8e-9199-bb9f3a64b4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c65147b4-da96-469d-a106-f3206c28a36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>2af743e1-c7c2-4606-96ab-a8a1f20d2732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-34&quot;)</value>
      <webElementGuid>acb162c2-21b1-413c-83f6-b4917acbf8ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-34']</value>
      <webElementGuid>5d9a3f87-c005-4995-8381-066565a2532a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenunjang-34']/div/div/form/div/div/input</value>
      <webElementGuid>7f20a46e-7063-4e34-b80f-f5f81a812f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/table/tbody/tr/td[7]/div/div/div/form/div/div/input</value>
      <webElementGuid>8b2a5192-23cc-46e0-9e0b-7ed0bb9914bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama-34' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>7d3f99ee-b800-469d-ad58-cb4513fcd823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
