<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (74)</name>
   <tag></tag>
   <elementGuidId>4044ff69-7e17-4b8a-b09f-272f74d37611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#penunjnag_nama_J</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='penunjnag_nama_J']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b57cf768-0298-4ebc-90a1-2cc133681c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjnag_nama_J</value>
      <webElementGuid>bff411f6-eb29-4105-a2f2-17ae43a3e07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>1824646e-56d8-4917-afd1-3790dca4ad47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>353557e3-3e49-4e0f-ab40-e9cf6d4e5ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>762bf3a4-0b26-496f-a793-c29812ddc4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjnag_nama_J&quot;)</value>
      <webElementGuid>120b21a7-10a2-40b5-8d8b-4067694c1dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='penunjnag_nama_J']</value>
      <webElementGuid>931943c8-4164-4b39-9a06-638aaf570579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_J']/div/div/div[2]/form/div/input</value>
      <webElementGuid>9184ab9b-fe2b-47a3-8af7-e48f1886d2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div/div[2]/form/div/input</value>
      <webElementGuid>87e82c5f-2ba8-4bb8-90cc-bbe8354f4699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'penunjnag_nama_J' and @name = 'nama_kegiatan' and @type = 'text']</value>
      <webElementGuid>80845d60-f3e7-4491-98c7-965106c5b586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
