<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SKS Mata Kuliah_sks_matakuliah (4)</name>
   <tag></tag>
   <elementGuidId>a3fcf54c-901c-4549-91b4-054cb5b1e152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_sks_A']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pend_sks_A</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0459efd3-fabb-4212-8771-433b58a20e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_sks_A</value>
      <webElementGuid>a24376fa-76e3-4257-ad10-38f76b60e008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>953ec7e5-b98a-495b-93eb-7edf5e6af695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>103659b2-fac8-46a8-93c3-c162e56d6a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sks_matakuliah</value>
      <webElementGuid>31c42664-d3d1-44d6-8b43-82465236e0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>420fb41f-9e7e-4828-8a78-68f74eb271a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>884a207d-0c05-43fb-9705-21fee9c1a40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_sks_A&quot;)</value>
      <webElementGuid>4b35b830-65e2-4248-b4e2-5a429f245b14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_sks_A']</value>
      <webElementGuid>bc679171-523e-44ea-9f69-4730420e161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_A']/div/div/form/div/div[4]/input</value>
      <webElementGuid>70b307f7-2509-44a0-93ca-25c936688d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/input</value>
      <webElementGuid>27d10c4e-a054-4335-9f4a-41c526a9fbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_sks_A' and @type = 'number' and @name = 'sks_matakuliah']</value>
      <webElementGuid>ceabe87f-6ae3-4ffc-9511-b4efc1c7dd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
