<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (46)</name>
   <tag></tag>
   <elementGuidId>29ba1b14-41f3-4a8a-ac81-9f66ccf88325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nama-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98632777-7426-4766-bfc6-259b775ae132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-19</value>
      <webElementGuid>519b5270-36d5-4621-8609-724b1bb721c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test Pendidikan J 1</value>
      <webElementGuid>1d7b4520-e9cf-4abd-a28e-5d21aa0bbee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a8c448e-5d78-4469-a230-59079d807631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3152b1f7-74de-4fe1-8a48-643e669d7b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>4308b540-b441-44a0-b3e6-b2995a05b202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-19&quot;)</value>
      <webElementGuid>e9264173-02ad-4823-a060-a23400a06a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-19']</value>
      <webElementGuid>03ff1b58-cee5-4491-9d3b-893d09ac934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan-19']/div/div/div[2]/div/input</value>
      <webElementGuid>e91a250e-349f-401b-944c-e4b1dbbc2620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>cc51aa20-f890-4a20-b8c2-10b10c93b592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama-19' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>22cbf165-cea9-46fa-97cf-c465b1118c9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
