<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (32)</name>
   <tag></tag>
   <elementGuidId>50a0c3ab-6954-4f00-ae15-5ab558881158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_nama_G']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pend_nama_G</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>470c88f1-a3a0-4d47-8de1-1cea2fed99cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_nama_G</value>
      <webElementGuid>f9d6aee4-cdb1-423c-9b79-bfdf1fa9f6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f25c4d4-8e71-4796-8d21-b34ddc4ea17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5ac637e-ef70-4500-943d-e7ada44b96d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>d7940fbb-2e2e-4002-afaa-6be847861708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_nama_G&quot;)</value>
      <webElementGuid>f6a48b70-5784-40cb-9c1b-ac4d9bda7e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_nama_G']</value>
      <webElementGuid>56dd2074-365a-4277-8221-38eb07c885a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_G']/div/div/div[2]/form/div/input</value>
      <webElementGuid>a7f881d1-347e-4103-910e-7ceb5b69c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div[2]/form/div/input</value>
      <webElementGuid>bad1df53-2619-4e1f-bda7-090901a58eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_nama_G' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>9177f05d-62b1-4026-81f7-0c4d22b3623a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (32)</name>
   <tag></tag>
   <elementGuidId>9acc55bf-92b2-497a-88d7-43d90372d005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='penunjang_nama_E']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#penunjang_nama_E</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f7cff95-b057-4e97-97ee-753d216954f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjang_nama_E</value>
      <webElementGuid>25eb24a4-ecbc-4c2f-9b36-b3293f3c62fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0066771-a049-4a6e-8af2-0387f6c3d9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>525f6f10-7ade-4bbd-9ca8-7d24903e3c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>34402c6b-aaec-4665-9f9a-1d32010e8435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjang_nama_E&quot;)</value>
      <webElementGuid>5e1bbffd-9cd0-4117-836d-56d769151afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='penunjang_nama_E']</value>
      <webElementGuid>2eb776f2-7806-46f9-a492-ee6230e86d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_E']/div/div/form/div/div/input</value>
      <webElementGuid>da655438-86cf-4bdf-bed4-27580bd00820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/form/div/div/input</value>
      <webElementGuid>41aa5ea0-5ea5-4535-8e7e-1301eb96663d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'penunjang_nama_E' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>275feeb3-44c1-4b39-8d3f-c11f1009e6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
>>>>>>> 8a8f20fa9ebde034c1c19771418b225d06099da6
