<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Dosen Dibimbing_jumlah_dosen (4)</name>
   <tag></tag>
   <elementGuidId>0cc04cb7-dc01-43ea-9d65-93098df5bcb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dosen-13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dosen-13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33aedb21-f406-42a7-a468-dd39f7d04568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dosen-13</value>
      <webElementGuid>81fb6e0e-e04d-4f22-b59a-0d1a12d96f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_dosen</value>
      <webElementGuid>2452748f-8dd5-431d-b569-ee47cb86ec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f868a666-0283-4125-9ead-fc1d565980e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1a9d983-bd59-43b4-b7b5-68941d200045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4abb74bf-fefd-44be-94a4-8d99e88d8540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dosen-13&quot;)</value>
      <webElementGuid>280fee46-78ff-4239-8355-9dcfaf8f41b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dosen-13']</value>
      <webElementGuid>3c84d9c8-3932-49b9-8619-1b2663a4f395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan_13']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>81be6c9f-6bb7-4d92-9594-dc6e0bec2be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>cf290489-0d55-4a92-a8d2-67aedac80d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dosen-13' and @name = 'jumlah_dosen' and @type = 'text']</value>
      <webElementGuid>f2e9e920-6288-46ce-b886-00f1b266ada4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
