<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah                               _2881e4 (3)</name>
   <tag></tag>
   <elementGuidId>b033d691-dca9-46f5-b774-1229e76292bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mahasiswa-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mahasiswa-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d97a3463-f141-4b79-82f9-3a884c4b4850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mahasiswa-2</value>
      <webElementGuid>52524597-14ed-4c6c-90b8-eb7d632cf629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>21332cd0-d3e8-4999-91ff-d8afc20a6c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ef4c7f7c-cf74-4383-9dd1-de8727f2cec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dd3143dc-d04f-4679-bb96-e4b2e622c3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_mahasiswa</value>
      <webElementGuid>6483de7f-1209-4a47-8f09-f607814b23df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5df13128-a438-4e73-af67-f25b88d14e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mahasiswa-2&quot;)</value>
      <webElementGuid>ea5a7beb-f9a3-4252-9c26-ad2e5d75438d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mahasiswa-2']</value>
      <webElementGuid>5f2bd397-ba95-4c64-90d4-39253b5da9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenunjang-2']/div/div/div[2]/div[2]/input</value>
      <webElementGuid>6c9c32b3-a916-4a03-be85-881bae2bb8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>72ae6326-0592-411c-9c93-b1574a0c242e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mahasiswa-2' and @type = 'number' and @name = 'jumlah_mahasiswa']</value>
      <webElementGuid>e4691653-ef59-481c-bda5-101b88c2c79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
