<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama                                 _c3a99b (14)</name>
   <tag></tag>
   <elementGuidId>5bbdc7ec-e216-44b9-a10a-67213cacad2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60fafbca-2f50-4b10-9157-e276320effe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-1</value>
      <webElementGuid>5d7c5d3d-15e4-418a-a95d-30f1a53edece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Melaksanakan perwalian mahasiswa</value>
      <webElementGuid>5dc741e1-ece4-49e4-8bbe-e0981b8d8253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b929f24-89e8-4988-87b7-a1c85ae3e7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8f323944-8679-4065-b099-8afd1277a4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>af77e377-b016-4c8b-8eec-544b8aaf18cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-1&quot;)</value>
      <webElementGuid>4e954f96-d8f5-44ef-b965-4435d7b99110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-1']</value>
      <webElementGuid>decd2585-b9d8-4983-9762-73881808296f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenunjang-1']/div/div/div[2]/div/input</value>
      <webElementGuid>e18217e6-3dbf-41a0-a6d4-7e4a57743651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e2fcad40-15ef-44ba-94f5-09f146a518aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama-1' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>725feded-69af-4cda-bfe2-ed71edda5044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
