<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Kelompok_jumlah_mahasiswa</name>
   <tag></tag>
   <elementGuidId>806798be-0402-4a2d-b2f7-a39782da5b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_kelompok_F</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_kelompok_F']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcc7925a-1ba3-4d40-9601-dafc6084c668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_kelompok_F</value>
      <webElementGuid>3b6c1ea6-75a6-43cc-b66d-d653d556be76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_mahasiswa</value>
      <webElementGuid>748fbdcb-aef3-4993-8157-568827993196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d990534d-0dbd-4936-9622-5f8ab8b9c044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>80db3463-76c4-4cd5-9fe6-ae9ad13f1d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_kelompok_F&quot;)</value>
      <webElementGuid>377a0d9b-8111-4760-9e2f-5897700a2130</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_kelompok_F']</value>
      <webElementGuid>fdfa3052-789f-4c9a-8867-6182c8a1a0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_F']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>767948bb-ef1d-46c1-b14a-9041b90ef15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>febb4cb0-b0f6-4ec1-92f9-690742bfb13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_kelompok_F' and @name = 'jumlah_mahasiswa' and @type = 'number']</value>
      <webElementGuid>804e7bf5-a7c7-4cbb-a827-9b4ecc0bab26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
