<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SKS Praktikum (1 SKS  2 jam)_sks_matakuliah (2)</name>
   <tag></tag>
   <elementGuidId>5524eb9e-9639-4f30-bfb6-4f929d39ac48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sks-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sks-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19d011a5-6132-4609-b0e3-56cda07f5dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sks-2</value>
      <webElementGuid>4169ab79-5e0f-4928-b350-31c8ecba9043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>54c72357-59fa-475e-a427-04d9aff093d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ca1e1e6f-8c09-4194-bfe9-250766242ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>55798733-573c-4830-8545-9ac134681b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sks_matakuliah</value>
      <webElementGuid>7649e4a1-3802-46fc-bc19-a751dcdcef52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>37908fc6-7627-4b35-b14a-b4bb9c05ca50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sks-2&quot;)</value>
      <webElementGuid>44318f10-2b17-4533-934e-498b4d190556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sks-2']</value>
      <webElementGuid>471ab66e-df28-4b55-acae-15e83e9ea984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan-2']/div/div/div[2]/div[3]/input</value>
      <webElementGuid>ef7ede99-e2ce-443f-a5f3-fd6e3030a00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>1d5b4090-736a-445f-b996-ffcc2b26f784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sks-2' and @type = 'number' and @name = 'sks_matakuliah']</value>
      <webElementGuid>957295d1-ec90-42af-8832-28dba5abab15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
