<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Mahasiswa Bimbingan_jumlah_mahasiswa</name>
   <tag></tag>
   <elementGuidId>a62a08db-e3c4-40b7-9107-3363325c97f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_mahasiswa_C</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_mahasiswa_C']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>353faa47-04a5-487b-894d-7c2cc325501b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_mahasiswa_C</value>
      <webElementGuid>60d74a6d-827e-4ba0-ab48-2b8560feb666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d7e7ff39-6a22-4aca-ab5e-f86d6445a181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0a33d3c-f3fc-4335-baf9-ccb53d1183e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_mahasiswa</value>
      <webElementGuid>3b4cfbe1-488b-4961-a4b8-eb5bf95c962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e96520e5-393b-4d29-a71f-8f7a8291d568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>4ca0673f-7747-46be-9894-589efce7b1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_mahasiswa_C&quot;)</value>
      <webElementGuid>26bc40d6-9a64-451e-a80d-4e6c3ca800c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_mahasiswa_C']</value>
      <webElementGuid>a81f4316-5c52-4553-8b12-69b397090efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_C']/div/div/form/div/div[2]/input</value>
      <webElementGuid>73b4a187-2b77-40d4-98c5-844e59d482f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/form/div/div[2]/input</value>
      <webElementGuid>0ccb77df-9a4f-4224-accf-b414259d9bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_mahasiswa_C' and @type = 'number' and @name = 'jumlah_mahasiswa']</value>
      <webElementGuid>9cc68e4c-1ed8-45a5-81c5-ca7e273c8557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
