<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Kelompok_jumlah_kelompok (2)</name>
   <tag></tag>
   <elementGuidId>57a7721b-b518-490a-8af9-c44a03a911b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_mahasiswa_E</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_mahasiswa_E']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c97481a0-61ac-4581-be94-65bc26d846b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_mahasiswa_E</value>
      <webElementGuid>f8e0985d-8290-4eb4-ad47-764f56b486d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_kelompok</value>
      <webElementGuid>261f127e-e48f-4ae6-8af1-eef4d9812881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8024aabf-4759-4849-9b13-69279f7c9045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>62ee8bb1-a2f1-4ca5-9384-03b1b29613c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7986441b-5c9c-4c83-909e-ed2d1da2c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_mahasiswa_E&quot;)</value>
      <webElementGuid>8dc63dd2-b19d-48e0-b99a-cb72068c23c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_mahasiswa_E']</value>
      <webElementGuid>e8259934-a552-4a68-a74b-1ba3869093cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_E']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>f9293949-7060-469f-a5a3-2076ac00c911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>017dff21-c356-4fa7-87cd-dca02edaaa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_mahasiswa_E' and @name = 'jumlah_kelompok' and @type = 'number']</value>
      <webElementGuid>07e54d6b-6814-4d52-a9ff-e03ad64edcba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
