<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kegiatan_nama_kegiatan (8)</name>
   <tag></tag>
   <elementGuidId>097ac5ca-f2a1-4858-9877-30215cd135b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_nama_E</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_nama_E']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2acbdc6-5afc-4174-bf0f-58a0406b5fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_nama_E</value>
      <webElementGuid>70bde5e5-e52d-44ec-8c56-2f2e7285cc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08ccb884-dee2-45d6-a4ed-92895b630146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62a3e4e9-8bf4-4f51-892f-bebda90d5926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>a5636c9f-e97a-4793-b83d-3fff5e05d493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_nama_E&quot;)</value>
      <webElementGuid>84ea7d84-e426-4b2d-a6e1-b9e9c4be537d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_nama_E']</value>
      <webElementGuid>53028cdd-57fd-4e00-ad59-e400afd62b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_E']/div/div/div[2]/form/div/input</value>
      <webElementGuid>4a4b9482-3cd7-47a9-ba03-806810cf1ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div[2]/form/div/input</value>
      <webElementGuid>823aafce-1141-4a84-a8dd-66a13acaa408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_nama_E' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>d4bdbce5-4a4f-4a0a-a433-9afa678ca824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
