<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama                                 _c3a99b</name>
   <tag></tag>
   <elementGuidId>e755ef6b-5492-4250-9d7a-193fbecd4336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>127ec64a-ee44-434d-997c-520142c4225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama-1</value>
      <webElementGuid>e996a23f-3ff0-423c-8581-a1a4df054538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kelas Teori Pada Tingkat S1</value>
      <webElementGuid>015ca0c1-345b-4176-b518-f7946c0328f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>236007b2-5922-4f0e-b0f2-d1696529a876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c0f611df-e02c-4398-a52e-098c9de1a2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>42cb24ee-a6f9-410f-83ba-63f3e06e5b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama-1&quot;)</value>
      <webElementGuid>3a13b671-9385-4dee-ac51-4d137c706f01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama-1']</value>
      <webElementGuid>2ffd6c6f-56e1-4903-b700-7fa26315b448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPendidikan-1']/div/div/div[2]/div/input</value>
      <webElementGuid>b1b168ac-45e7-4008-86b5-441f2adaf0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8d94bbb7-8c2d-4232-a0d8-a58000dae517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama-1' and @type = 'text' and @name = 'nama_kegiatan']</value>
      <webElementGuid>f9a856da-1710-43aa-8d7b-14c808f5b04b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
