<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SKS Praktikum (1 SKS  2 jam)_sks_matakuliah</name>
   <tag></tag>
   <elementGuidId>6910422d-ef51-4fb4-9ec2-63f44b038186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pend_sks_B</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pend_sks_B']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d20406f-f652-4e3d-b19f-5c4242c4942d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pend_sks_B</value>
      <webElementGuid>dd41c346-227c-440a-b71b-cb1ff202f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sks_matakuliah</value>
      <webElementGuid>3b498f0a-adf7-4db7-99cb-91390c2d06de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>145b2010-d5e4-4f09-8811-87634032d7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c34e58f4-908e-4fad-8d63-74d367afe515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>718b4f5d-533d-4063-80b7-6854b71f7a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>5af8bf92-f6be-4ba8-87a4-9414ff7d51e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pend_sks_B&quot;)</value>
      <webElementGuid>b0d01c9f-da56-436e-924d-87321bf692f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pend_sks_B']</value>
      <webElementGuid>cab9019e-0cc1-429e-a08d-8759318a28aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPendidikan_B']/div/div/div[2]/form/div[3]/input</value>
      <webElementGuid>d3365945-ce70-4ce8-8ac7-43661e7d6cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>b6aeed34-7cf8-4ffa-aefc-384a5acf8be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pend_sks_B' and @name = 'sks_matakuliah' and @type = 'number']</value>
      <webElementGuid>4e443225-33dc-4c6d-b7de-a33d2f0aff15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
