<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nama Kegiatan (4)</name>
   <tag></tag>
   <elementGuidId>3aad8da7-6364-4502-a74a-a2f86307e936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPenelitian_E > div.modal-dialog.modal-dialog-centered > div.modal-content > form.formTambahData > div.modal-body > div.mb-3 > label.form-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalPenelitian_E']/div/div/form/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>201ced3e-2f69-4a30-8d2e-87726a397b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>46a8e068-3d48-455b-bec6-71a37a046cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>08752987-5c4f-45e5-b4c3-9ff13e075a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Kegiatan</value>
      <webElementGuid>2a95680f-2643-4737-ad94-c8362d31e2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPenelitian_E&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;formTambahData&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>0a20feea-727e-4eb6-bd5b-a65efcb8958b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenelitian_E']/div/div/form/div/div/label</value>
      <webElementGuid>c922698d-219c-419d-b127-db265e0d393c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[6]/following::label[1]</value>
      <webElementGuid>1fbff807-a3a6-4d3b-a463-aab0b190e44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peran'])[8]/following::label[1]</value>
      <webElementGuid>f0086d93-7877-43d5-8643-e768612084a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahap Pencapaian'])[15]/preceding::label[1]</value>
      <webElementGuid>ddc78dee-3b6f-4b20-8fe0-35586e651f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi (Ketua/Editor/Anggota)'])[3]/preceding::label[2]</value>
      <webElementGuid>a71523f1-a04b-48e7-8c19-13ce1ff46504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/form/div/div/label</value>
      <webElementGuid>e1201420-9c5f-496c-bee2-4faa31db9afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nama Kegiatan' or . = 'Nama Kegiatan')]</value>
      <webElementGuid>ef9a47b3-0b8b-429a-b50b-1c8bfe4bc7f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
