<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Jabatan                       _3dfe88 (1)</name>
   <tag></tag>
   <elementGuidId>2d6d399e-0ad2-46b2-b8bc-5934eb66f00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='posisi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#posisi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87160567-b89c-473d-b045-e58d9122d7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>posisi</value>
      <webElementGuid>281a2ae5-e487-461b-907d-ef40ce28ff50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posisi</value>
      <webElementGuid>0626cfc1-e951-4f25-97a3-d3850a7b661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-md mb-3</value>
      <webElementGuid>559f1e8c-7155-4080-83ce-449e7e4a2d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>.form-select-md example</value>
      <webElementGuid>161ba385-ba37-4705-8e43-b56043b272ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Pilih Jabatan
                                Ketua
                                Anggota
                            </value>
      <webElementGuid>010de938-f666-411e-8365-9967a8e0e66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;posisi&quot;)</value>
      <webElementGuid>603fd920-61c7-489a-bdc5-c50a5d75384b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='posisi']</value>
      <webElementGuid>0e7dc929-78ba-4ddf-9d1f-3931be82be69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalpengabdian_C']/div/form/div/div[2]/div[2]/select</value>
      <webElementGuid>9fcf2486-4a39-46fa-b96d-9b3a5e978a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2383ae9a-efda-4213-b657-98cfc57bb283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'posisi' and @id = 'posisi' and (text() = '
                                Pilih Jabatan
                                Ketua
                                Anggota
                            ' or . = '
                                Pilih Jabatan
                                Ketua
                                Anggota
                            ')]</value>
      <webElementGuid>03a80d09-0f16-4bae-99cf-69a05c97495b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
