<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Open this select menu               _ab0fea (4)</name>
   <tag></tag>
   <elementGuidId>395f8c0b-d02f-4453-a8b0-dad98ba3a325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='penunjang_tingkatan_J']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#penunjang_tingkatan_J</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eae0d856-7cd2-4bda-953e-ea5d06b9285e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjang_tingkatan_J</value>
      <webElementGuid>611265e5-67ac-433e-b4e3-b01c8731091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_tingkatan</value>
      <webElementGuid>e24eda7b-1459-4c8e-aa51-d295c95fd408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bf330c25-a353-44cd-a8c4-01ccbf0b5c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Open this select menu
                                Universitas
                                Fakultas
                                Program Studi
                            </value>
      <webElementGuid>e52a3ec7-dad4-4d95-a4f7-4a80dd4138b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjang_tingkatan_J&quot;)</value>
      <webElementGuid>6d460e88-2ae1-4785-8f42-89cd9547e281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='penunjang_tingkatan_J']</value>
      <webElementGuid>8e184a36-8b96-4886-aafc-2d01c3a5b7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_J']/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>54512b6b-97aa-4e8d-93bc-978e4ef4f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkat Jabatan:'])[2]/following::select[1]</value>
      <webElementGuid>ed161740-9ae5-4c74-89de-d3d8afe2c641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kegiatan:'])[4]/following::select[1]</value>
      <webElementGuid>c6b188a5-7f9e-4caf-befb-4c20922e9703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[10]/preceding::select[1]</value>
      <webElementGuid>3d7c8073-d880-4869-b759-614a25eae1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div/div[2]/form/div[2]/select</value>
      <webElementGuid>39055a0f-21fb-49ce-b2d9-2e33dbac51a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'penunjang_tingkatan_J' and @name = 'jenis_tingkatan' and (text() = '
                                Open this select menu
                                Universitas
                                Fakultas
                                Program Studi
                            ' or . = '
                                Open this select menu
                                Universitas
                                Fakultas
                                Program Studi
                            ')]</value>
      <webElementGuid>96c8d262-1c32-48db-932c-4810eea13ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
