<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Open this select menu               _ee553e</name>
   <tag></tag>
   <elementGuidId>88c5617a-fa04-4608-965a-4b21a45fc9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='penunjang_tingkatan_L']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#penunjang_tingkatan_L</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2e68e01d-1c82-4d4b-9d39-3f3ffc818d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penunjang_tingkatan_L</value>
      <webElementGuid>ed1a5714-b3a9-447d-8690-94299d8db49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e1073ed9-8fb9-4d40-92d4-4e614648a7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_tingkatan</value>
      <webElementGuid>5850c5a3-e8e6-4977-8493-c10ee7eb927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Open this select menu
                            Nasional
                            Internasional
                        </value>
      <webElementGuid>c6f75c4f-0786-4660-9056-fe1b034bff78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penunjang_tingkatan_L&quot;)</value>
      <webElementGuid>9984ae48-7897-487b-9206-e2a3e127420a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='penunjang_tingkatan_L']</value>
      <webElementGuid>9f6d6e8d-2dd8-48fa-a96f-edba6d099d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_L']/div/div/div[2]/form/select</value>
      <webElementGuid>cddf50ef-f8cc-4c68-855d-bcaf3c43098a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkatan:'])[1]/following::select[1]</value>
      <webElementGuid>e3caf67c-95f1-48df-9dfa-38f4e9a3ba27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabatan:'])[2]/following::select[2]</value>
      <webElementGuid>76583a06-ab99-41a4-92a6-90c0a683449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[12]/preceding::select[1]</value>
      <webElementGuid>63667f44-87da-4e82-96d6-f348832df8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M. Peserta Seminar/Workshop/Kursus Berdasar Penugasan Pimpinan'])[2]/preceding::select[1]</value>
      <webElementGuid>bb557d85-10a2-40f8-b1e0-949cbdc8e0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/select</value>
      <webElementGuid>65d4f915-dc63-44cf-9803-75f99974af7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'penunjang_tingkatan_L' and @name = 'jenis_tingkatan' and (text() = '
                            Open this select menu
                            Nasional
                            Internasional
                        ' or . = '
                            Open this select menu
                            Nasional
                            Internasional
                        ')]</value>
      <webElementGuid>8f9e7814-0d8b-45ab-b681-4c91810286fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
