<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>1121b9bb-0dbc-41b4-9876-63b13038a7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePendidikan-G > tbody > tr > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-G']/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bbd62ac3-fdf0-40ec-835a-f8d419e07ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e5db5d4b-ed74-49c0-ad28-37d2c1b3467a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-G&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>fe764254-2223-49c0-883b-6fc5dcc006d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-G']/tbody/tr/td[3]</value>
      <webElementGuid>440900da-300a-4ad1-a100-b661219077a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membimbing dosen baru'])[1]/following::td[1]</value>
      <webElementGuid>d21c105a-75fd-41c9-988b-667a4ed02419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[7]/following::td[3]</value>
      <webElementGuid>232df5df-9b53-4432-af74-836704708f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[13]/preceding::td[2]</value>
      <webElementGuid>638d53d8-9789-4c03-bed1-707a47a68630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[14]/preceding::td[3]</value>
      <webElementGuid>ff7a434f-b66f-48db-bef6-9392e581a8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>d226bd44-0778-423d-a066-6187939e7b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1' or . = '1')]</value>
      <webElementGuid>16593416-75ce-4a99-a650-1cae2e415289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
