<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3</name>
   <tag></tag>
   <elementGuidId>57122b6a-9089-46f3-b56d-2ab3db1ee553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePendidikan-H > tbody > tr > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-H']/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>190b583d-6ae1-47d0-a080-5b20f3ebe5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0b81c7df-5c18-452b-8e7f-51f2a2758191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-H&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>2fa6ee2b-2bf8-42e6-a2a6-d41e32c68e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-H']/tbody/tr/td[3]</value>
      <webElementGuid>a1a63927-7d8e-4183-aa54-0d26cae54f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memperbaharui Silabus'])[1]/following::td[1]</value>
      <webElementGuid>fafc2c71-8b86-4645-9b9d-3c60539191c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[8]/following::td[3]</value>
      <webElementGuid>59c359c6-d600-4a5e-840f-24957abcb1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[15]/preceding::td[2]</value>
      <webElementGuid>e9325a40-8f0d-48bd-b759-4740da40fcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[16]/preceding::td[3]</value>
      <webElementGuid>b10fcd1b-5dcd-4526-9a67-2b95779843d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>7a6e99e3-ec58-4393-90a3-0a25d1172216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>bcc2164e-22c1-476b-9499-8a1a9198bd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '3' or . = '3')]</value>
      <webElementGuid>1def03b2-e888-4843-89a8-5b5b895f0855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
