<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ketua</name>
   <tag></tag>
   <elementGuidId>25b35d94-0263-459b-8e50-54e0abb80af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-K']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-K > tbody > tr > td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5fb182d6-c8b8-4504-a02f-c558f3494bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ketua</value>
      <webElementGuid>0f1c0614-641d-48bb-92b1-a0797dbd7361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-K&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>9c5e442f-e1a6-4171-8bbf-9faae5f2f0bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-K']/tbody/tr/td[3]</value>
      <webElementGuid>b1bfcc1b-8aaf-457e-b871-68498ac09d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengurus BAN-PT'])[1]/following::td[1]</value>
      <webElementGuid>74b8f513-4cf2-4068-85fc-cca7d02e1286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[11]/following::td[3]</value>
      <webElementGuid>73fac5b5-b0d4-41f3-a14b-4a931ffa372b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[83]/preceding::td[2]</value>
      <webElementGuid>2a764345-68a3-4e41-99cd-5973a7c73337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[84]/preceding::td[3]</value>
      <webElementGuid>3e6f40ae-0ed0-4e24-b56e-30c6b59988b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ketua']/parent::*</value>
      <webElementGuid>7f62c22a-93ed-4687-9c42-96859106d92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>a46945e0-815a-4e2e-881b-0e7f57643990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Ketua' or . = 'Ketua')]</value>
      <webElementGuid>84e2e130-640f-4356-9c32-f6acada0f321</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
