<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ka Biro atau Ka Lembaga</name>
   <tag></tag>
   <elementGuidId>1dc2222a-b4a7-4eaf-acd9-12a501a9fdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-E']/tbody/tr[10]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(10) > td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ee9987dc-7cc8-4903-ab43-48f7ef4ac2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ka Biro atau Ka Lembaga</value>
      <webElementGuid>c44036a8-87f7-41ab-a6ec-9837bed1fb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-E&quot;)/tbody[@class=&quot;align_middle&quot;]/tr[10]/td[3]</value>
      <webElementGuid>bbb8d828-d67a-4c47-a891-d40f599dcb58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-E']/tbody/tr[10]/td[3]</value>
      <webElementGuid>fcd2376d-939d-40b4-a0d1-4288bbb1af2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengembangan Program dan Proyek'])[1]/following::td[1]</value>
      <webElementGuid>98dc5107-5ff9-480b-bbd3-f17c130b7cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin'])[13]/following::td[3]</value>
      <webElementGuid>6073c417-ad7f-477e-bd19-25e777fd4798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[27]/preceding::td[2]</value>
      <webElementGuid>12bef54b-2e9a-4dd7-8c8a-0d05b1cf7c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[28]/preceding::td[3]</value>
      <webElementGuid>85a6f17e-d93a-4f3e-bb8d-72df5f7a3ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[3]</value>
      <webElementGuid>47afe86f-3fcf-4074-b963-f2c1de5587cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Ka Biro atau Ka Lembaga' or . = 'Ka Biro atau Ka Lembaga')]</value>
      <webElementGuid>09ac42cc-f1a4-430e-8f65-fd5d610d8116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
