<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu (8)</name>
   <tag></tag>
   <elementGuidId>bfb634ef-67a0-472f-81a7-7fe6aeb59ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePendidikan-F > tbody.align-middle > tr > td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-F']/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>71fc668b-71b9-4e30-94c7-c91f92144505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Menunggu
                                                                            </value>
      <webElementGuid>ba730341-204d-44f4-9680-9bd0f881db98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-F&quot;)/tbody[@class=&quot;align-middle&quot;]/tr[1]/td[5]</value>
      <webElementGuid>268ab461-1267-4907-af46-6d027d677c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-F']/tbody/tr/td[5]</value>
      <webElementGuid>48d34f49-f730-4b01-8de9-5a0f4360696c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menguji proposal S1'])[1]/following::td[3]</value>
      <webElementGuid>5c6bba85-2333-42f0-8a11-716ead7288bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[6]/following::td[5]</value>
      <webElementGuid>febbe3e2-102b-45e4-8d99-ba31fb785da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[12]/preceding::td[1]</value>
      <webElementGuid>99e5358a-80f2-41b6-9dc0-23b58e518c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>c818929b-219f-4a74-8df3-77a4ba684cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Menunggu
                                                                            ' or . = '
                                                                                    Menunggu
                                                                            ')]</value>
      <webElementGuid>1a19c540-5396-4982-8b1d-434163d6c6b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
