<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu (17)</name>
   <tag></tag>
   <elementGuidId>109ab0e9-7f84-4b1c-88f4-44a48a3a3273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePendidikan-B > tbody > tr > td:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-B']/tbody/tr/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f38d6bf1-12b4-4d84-a988-27dcce43682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Menunggu
                                                                            </value>
      <webElementGuid>b43c09e3-25ca-42f4-b37a-f61f52d3ce73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-B&quot;)/tbody[1]/tr[1]/td[6]</value>
      <webElementGuid>30816be9-8b5f-4520-9744-2cc0a9d5dcb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-B']/tbody/tr/td[6]</value>
      <webElementGuid>a92aaffb-f5a8-43c2-9706-44c088829cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asistensi Praktikum Kelompok'])[1]/following::td[4]</value>
      <webElementGuid>35867783-20c7-4d7a-b718-6649bf9eaa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[2]/following::td[6]</value>
      <webElementGuid>707f6a73-7a93-42bf-9ea0-5b59725be7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[4]/preceding::td[1]</value>
      <webElementGuid>65b712f5-cf98-49f5-b913-1b8640da04c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/table/tbody/tr/td[6]</value>
      <webElementGuid>aca18667-474b-41ab-9f0f-9afacd1a6274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Menunggu
                                                                            ' or . = '
                                                                                    Menunggu
                                                                            ')]</value>
      <webElementGuid>76424891-ce87-4055-8069-47fdfcab51f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
