<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu_1 (5)</name>
   <tag></tag>
   <elementGuidId>c096ef4f-0bcd-43b9-8f43-14ab3b402019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tbody.align_middle > tr > td:nth-of-type(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-C']/tbody/tr/td[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>950308b7-f71f-4ce7-b4b5-bf5be1e0c36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            Menunggu
                                                                        </value>
      <webElementGuid>65dafa12-a75f-42ce-b845-1f2064b9729d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-C&quot;)/tbody[@class=&quot;align_middle&quot;]/tr[1]/td[6]</value>
      <webElementGuid>f26c3756-2622-4254-bf6a-1c652baf6960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-C']/tbody/tr/td[6]</value>
      <webElementGuid>28cf51eb-ac5c-4b3f-b1b7-a51ec2ac76af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[5]/following::td[1]</value>
      <webElementGuid>775fbe5c-c016-446f-b9f1-a9c65e9da6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembimbingan Praktek Lapangan'])[1]/following::td[4]</value>
      <webElementGuid>1bba5338-7616-4380-b78e-6dad2d6f9788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[3]/preceding::td[1]</value>
      <webElementGuid>3d36d74d-6ca5-4907-a898-69b8d3d9cc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/table/tbody/tr/td[6]</value>
      <webElementGuid>887517af-b307-4da1-8582-9dd1bc00f22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                            Menunggu
                                                                        ' or . = '
                                                                            Menunggu
                                                                        ')]</value>
      <webElementGuid>8bf7d3ed-7c4c-42cf-8b26-b9fbaa7ef64c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
