<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu (59)</name>
   <tag></tag>
   <elementGuidId>ca1ef0f4-5eb0-466c-b603-0fd800c7ffb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-F']/tbody/tr[7]/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-F > tbody.align_middle > tr:nth-of-type(7) > td:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2e68eb0f-5c1b-404a-95db-97ef1bf591a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            Menunggu
                                                                        </value>
      <webElementGuid>df1f02f8-f9b6-4e67-ac41-b9eee9285e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-F&quot;)/tbody[@class=&quot;align_middle&quot;]/tr[7]/td[5]</value>
      <webElementGuid>b52d588f-4f83-456a-b1f9-da1a92a91d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-F']/tbody/tr[7]/td[5]</value>
      <webElementGuid>0df45d00-93e9-4392-bd55-9dcaaa711e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ka GBK'])[7]/following::td[2]</value>
      <webElementGuid>f636ab79-bfcc-4e03-b35a-dec80420b5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perencanaan dan pengembangan infrastruktur'])[1]/following::td[3]</value>
      <webElementGuid>2837a8b9-37fa-4c0f-8dfc-4e233f1dc3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[58]/preceding::td[1]</value>
      <webElementGuid>8a25d1dc-94c2-40fc-924e-12fe9c81c846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/table/tbody/tr[7]/td[5]</value>
      <webElementGuid>c0701abc-d037-4225-a019-8d9f9339ad6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                            Menunggu
                                                                        ' or . = '
                                                                            Menunggu
                                                                        ')]</value>
      <webElementGuid>fa5bacc7-d716-41b3-a320-a0f4dcc9cda6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
