<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu_1 (47)</name>
   <tag></tag>
   <elementGuidId>23851664-eb12-4da7-a110-4ac026a8a678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-D']/tbody/tr/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-D > tbody > tr > td:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>573a97d5-b5d2-444b-8bb9-00437630eb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            Menunggu
                                                                        </value>
      <webElementGuid>865d5e5a-927c-4bfa-9754-3ae102841ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-D&quot;)/tbody[1]/tr[1]/td[5]</value>
      <webElementGuid>cc33c3b9-ab17-4128-b5b9-c5f8707254f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-D']/tbody/tr/td[5]</value>
      <webElementGuid>7df30f29-420e-4b22-a028-7845bfe2f77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[7]/following::td[1]</value>
      <webElementGuid>8e4ad03e-65a1-4459-9bbd-04382188aa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakil Ketua koperasi fakultas'])[1]/following::td[3]</value>
      <webElementGuid>0066f33b-fb1e-44e0-89de-83e2e7dd9a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yakin untuk menghapus kegiatan ini?'])[4]/preceding::td[1]</value>
      <webElementGuid>bfbbc831-8045-4a15-bd91-a42ec342f5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>ce41e34d-59b2-45b2-b9b3-725c616b7bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                            Menunggu
                                                                        ' or . = '
                                                                            Menunggu
                                                                        ')]</value>
      <webElementGuid>c5544cc9-b0ca-44be-91ea-5907b1eec9e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
