<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu (9)</name>
   <tag></tag>
   <elementGuidId>981d6641-9d66-4ed4-b913-3c291092b10d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePendidikan-G > tbody > tr > td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-G']/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>20c48ed3-0e71-45d3-8cc6-6076dd17be5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Menunggu
                                                                            </value>
      <webElementGuid>0d4ffbb5-eb0f-4350-b7ca-bf56805977e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-G&quot;)/tbody[1]/tr[1]/td[5]</value>
      <webElementGuid>178c81bb-c10b-4c5d-8018-e7ea883e18fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-G']/tbody/tr/td[5]</value>
      <webElementGuid>bb0c6071-c6fe-4612-9ed6-31afd8db502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membimbing dosen baru'])[1]/following::td[3]</value>
      <webElementGuid>e054d887-aa8c-4a20-b2d1-90750a0eae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[7]/following::td[5]</value>
      <webElementGuid>514c90de-9340-4815-8193-279cf22c3d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[14]/preceding::td[1]</value>
      <webElementGuid>92c966bb-2db8-4820-a15e-8041a68f88ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/table/tbody/tr/td[5]</value>
      <webElementGuid>66177d7a-ba8e-44fc-8da0-efdd13db6964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Menunggu
                                                                            ' or . = '
                                                                                    Menunggu
                                                                            ')]</value>
      <webElementGuid>2fede618-ee98-4417-9c0b-4e8871ef170d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
