<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Menunggu (104)</name>
   <tag></tag>
   <elementGuidId>23379d33-8e48-4b72-8319-1be1c6de3045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-D > tbody > tr > td:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-D']/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>68e5ed1b-1259-46ef-8713-4a026f6ebb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Menunggu
                                                                            </value>
      <webElementGuid>d323be59-0d99-48cc-8b44-f3bd04653a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-D&quot;)/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>48256a3b-12ce-4269-8085-ff5317eb62b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-D']/tbody/tr/td[4]</value>
      <webElementGuid>469fce2f-bc58-46ec-994a-f56e19f94cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakil Ketua koperasi fakultas'])[1]/following::td[2]</value>
      <webElementGuid>dad771c8-612d-42e4-ab69-04615dad5f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[4]/following::td[4]</value>
      <webElementGuid>cbd0875d-cc11-4021-87b5-52f43c494184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[8]/preceding::td[1]</value>
      <webElementGuid>01b5b731-a8a1-4ba7-ba4c-d8b6c4191b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/table/tbody/tr/td[4]</value>
      <webElementGuid>362f8128-c72d-4588-a090-59ac546287a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Menunggu
                                                                            ' or . = '
                                                                                    Menunggu
                                                                            ')]</value>
      <webElementGuid>708472f6-2016-4c5f-968e-3a04394b511d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
