<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Universitas</name>
   <tag></tag>
   <elementGuidId>a0fefad4-a1a2-4851-b6bc-1bac3734883e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePenunjang-I']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tablePenunjang-I > tbody > tr > td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6d19bcd6-176c-4e29-8406-e3c587f652a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Universitas</value>
      <webElementGuid>7f2bcbbd-85c0-4ae8-aca2-2caafbb49f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenunjang-I&quot;)/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>6bb5e3a4-19ac-41dc-ac64-65537b68eaa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenunjang-I']/tbody/tr/td[3]</value>
      <webElementGuid>ef436e1e-d114-489a-8678-4a0474c52069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengembangan Visi dan Misi'])[1]/following::td[1]</value>
      <webElementGuid>df2e8238-6cb3-4d76-a7e0-eb79b132601f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 2'])[9]/following::td[3]</value>
      <webElementGuid>71e809c2-0ee8-45ba-b3fe-19d1649841e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[71]/preceding::td[2]</value>
      <webElementGuid>608542fb-243e-4377-bac5-f50673483119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[72]/preceding::td[3]</value>
      <webElementGuid>e2bbf311-359b-48b5-aa44-2d185ad3ed05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>a5fc9333-b6d1-4a1b-a2b2-097ce42d06d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Universitas' or . = 'Universitas')]</value>
      <webElementGuid>995c038d-bb90-4c1b-b262-72f67f791d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
