<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Asesor 2</name>
   <tag></tag>
   <elementGuidId>e6cfa3cd-7ff4-4d2c-a8db-2a4ee7b14211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablePendidikan-F']/thead/tr[2]/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>5e6cb5de-ed4a-4e87-a8eb-68797f05a9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>c03b0b65-6cba-4a0e-9cd8-adb3a457dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold</value>
      <webElementGuid>d737fa0b-20c3-4d4b-b992-eb3de99dea65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asesor 2</value>
      <webElementGuid>60b697e0-c1a0-430a-8f8c-e7a1491455b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePendidikan-F&quot;)/thead[1]/tr[2]/th[@class=&quot;fw-bold&quot;]</value>
      <webElementGuid>9269500b-840c-4ca4-9c4a-517b6f7e49f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePendidikan-F']/thead/tr[2]/th[2]</value>
      <webElementGuid>1474a443-069b-419c-8509-85796c0fc69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asesor 1'])[6]/following::th[1]</value>
      <webElementGuid>5d1e51d2-3648-4310-b1fc-8e53a7ef5d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[6]/following::th[2]</value>
      <webElementGuid>359b75aa-b7f4-437e-bc58-30ba35c20f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menguji proposal S1'])[1]/preceding::th[1]</value>
      <webElementGuid>15d77eef-8e8f-41f0-8565-9b4513487eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu'])[11]/preceding::th[1]</value>
      <webElementGuid>90add906-1217-41a9-8327-d4bd7335393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/table/thead/tr[2]/th[2]</value>
      <webElementGuid>1ef32f24-9cf6-4b46-b9f8-90cf709568e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Asesor 2' or . = 'Asesor 2')]</value>
      <webElementGuid>20dbc817-c680-4f78-ac5a-7b012521c554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
