<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata                                 _617843 (1)</name>
   <tag></tag>
   <elementGuidId>bd964851-3045-41fd-9c58-ffe72fd92e1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typePasswordX']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typePasswordX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82a8fe06-3162-49fe-bb99-30e7dd1eb2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3c71c85f-07c3-4140-b8da-b61faf79a8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>25a0ce6d-1df9-4855-9e7e-c94ba19de0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typePasswordX</value>
      <webElementGuid>44177f47-f73d-4a60-9a60-d580ae24d814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow form-control form-control-lg border-dark </value>
      <webElementGuid>86c2d3f3-7277-4843-94a8-54fc84de9d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typePasswordX&quot;)</value>
      <webElementGuid>9d5773c6-230b-4a3a-9f15-102f7f4f9f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id2</value>
      <webElementGuid>29250d22-3d98-44d5-babb-14dc60249936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typePasswordX']</value>
      <webElementGuid>b4ada1f1-5b39-41ec-a037-3a07eeb28c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d62f15f6-1785-4cc0-8e04-eec75119a60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'typePasswordX']</value>
      <webElementGuid>1b3eeac3-ae6d-4f31-8943-b8b7d86ddb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
