<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username (191)</name>
   <tag></tag>
   <elementGuidId>d054acf0-1349-4668-ae6a-2b08bea821c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typeEmailX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typeEmailX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>243eadf1-914a-4463-84c1-ccb1cd8138e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eef61b6-4c6b-494f-9e0a-50463429b424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>cd516ac3-c217-4970-9a39-4cb307605b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeEmailX</value>
      <webElementGuid>bafadbf4-4e41-4ebf-8e21-9decbe2aa871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow form-control form-control-lg border-dark </value>
      <webElementGuid>134310c5-85c2-460f-a9d9-6b529870d95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeEmailX&quot;)</value>
      <webElementGuid>05eb590c-8871-4766-9f40-5e53bc41bbf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typeEmailX']</value>
      <webElementGuid>010086b5-853e-4ed8-8f15-262c602d12fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f6d4a278-3cdd-49ce-a183-9539d120ce3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @id = 'typeEmailX']</value>
      <webElementGuid>a7ac5b8c-d9e7-4146-a9ce-ceb899b52bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
