<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata                                 _617843 (112)</name>
   <tag></tag>
   <elementGuidId>081ef939-947e-4750-9c0c-6a68a2249cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typePasswordX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typePasswordX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab4d9bcf-4cc5-4bb5-865e-5ebfea621b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2b176ddc-ccf5-4a58-97a3-7ab3a437bb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ce765b26-beb2-4683-90c1-f424aed53b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typePasswordX</value>
      <webElementGuid>1d6723cd-3a88-4ae2-9726-4819ede8449a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow form-control form-control-lg border-dark</value>
      <webElementGuid>32263389-01e4-409f-b469-9720c0861cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typePasswordX&quot;)</value>
      <webElementGuid>3e4bc682-5f10-4de5-887f-6c75170a65af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typePasswordX']</value>
      <webElementGuid>e2193cd5-b676-46a5-8032-6ea2bd2d660d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>67fb2ab3-ebda-4ca3-b125-71eca363c430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'typePasswordX']</value>
      <webElementGuid>98f445b1-22c6-4ce3-9914-eb4cc0345d9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
