<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username (191)</name>
   <tag></tag>
   <elementGuidId>319bb964-2f76-45f1-a541-0353e2037536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typeEmailX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typeEmailX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c17390b-451c-4cfc-8c41-3b9330dc4e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6b7a4dc-e413-4fc7-a4bd-72943fac0d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>599dd69d-48c9-42b0-a977-6b77f6c5017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typeEmailX</value>
      <webElementGuid>cc33341f-ceb7-47c9-a7dc-ddacf773060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow form-control form-control-lg border-dark </value>
      <webElementGuid>0e4216a9-ee0f-4bf2-824c-c304a15e3dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typeEmailX&quot;)</value>
      <webElementGuid>0b6b702d-268f-4009-82ac-f57469915868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typeEmailX']</value>
      <webElementGuid>21d37b6b-e32a-4714-a76e-d9d4c8da4864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>fb6cd581-be6b-4e8f-93af-fd8b0bba63f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @id = 'typeEmailX']</value>
      <webElementGuid>8fd3d920-af3b-4a62-b71b-69ea3a70e8da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
