<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mpdf_21_1435_Penelitian_Kelompok1716799614.pdf</name>
   <tag></tag>
   <elementGuidId>230d8fce-8346-4b00-a851-5a349a141826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='existsFiles']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ms-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;mpdf_21_1435_Penelitian_Kelompok1716799614.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c4010ee-421a-4fea-adb5-bf15031c0240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk5NjE0LnBkZg==</value>
      <webElementGuid>4f037577-664d-4987-8ade-5a77edd2e89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>a2fcf298-04c8-46fa-8cc5-1b21297b610e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpdf_21_1435_Penelitian_Kelompok1716799614.pdf</value>
      <webElementGuid>65f5e673-df1c-48b7-954e-4430336c592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditEvaluasiPenelitian_A-21&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>f74392b7-a981-4b27-83fc-37312467294e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existsFiles']/div/a</value>
      <webElementGuid>31e857db-7a59-47e6-820e-c157ea1e0087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mpdf_21_1435_Penelitian_Kelompok1716799614.pdf')]</value>
      <webElementGuid>346eddaf-7a97-44ff-bd5b-d15976e52270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[1]/following::a[1]</value>
      <webElementGuid>3230cbef-d48c-458a-9b89-ffdf7c5ea305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan akhir penelitian (termasuklog book)'])[1]/following::a[1]</value>
      <webElementGuid>5ae7b154-c764-4e41-bb92-6a6c84cb3c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::a[2]</value>
      <webElementGuid>c2078cd4-514c-41e8-bd36-316b27e1c8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Lampiran'])[1]/preceding::a[2]</value>
      <webElementGuid>9eb5d9fd-34c9-4d87-a214-3869fb47dde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mpdf_21_1435_Penelitian_Kelompok1716799614.pdf']/parent::*</value>
      <webElementGuid>98ca286a-013d-4ac7-8068-379dab291b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk5NjE0LnBkZg==']</value>
      <webElementGuid>2a4da281-4ab4-4607-aef4-e43f7e7c3195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>dbd2bdb9-1232-4204-809f-0b5abb37d150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk5NjE0LnBkZg==' and (text() = 'mpdf_21_1435_Penelitian_Kelompok1716799614.pdf' or . = 'mpdf_21_1435_Penelitian_Kelompok1716799614.pdf')]</value>
      <webElementGuid>952c233d-948a-48d4-8b01-4ac469e52f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
