<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_P10_-_Measure_Performance_21_1435_Penelit_7d64c2</name>
   <tag></tag>
   <elementGuidId>e9312d68-de2c-488e-9161-fe1180b79f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='existsFiles']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ms-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>939106b1-a4f6-4b08-b7ae-aea3e6558bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk2NTA4LnBkZg==</value>
      <webElementGuid>1efe3418-2f86-4860-9ce2-8088af3f42b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>3714a474-4f09-4761-95a7-44832da4488c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf</value>
      <webElementGuid>531f5943-c802-49dc-9c6e-903d7a7a0d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditEvaluasiPenelitian_A-21&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>4e8e9bce-b36c-480b-b270-700702032dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existsFiles']/div/a</value>
      <webElementGuid>ac8e6a81-9fff-4e46-8ad7-8f3099984905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf')]</value>
      <webElementGuid>fa8925fa-9056-4b6d-8a81-61250df92d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[1]/following::a[1]</value>
      <webElementGuid>d44a2253-75a7-40ba-a519-8df67e8a9725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan akhir penelitian (termasuklog book)'])[1]/following::a[1]</value>
      <webElementGuid>39bc7ba1-fded-4e6b-af72-6be3b4edf3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::a[2]</value>
      <webElementGuid>d3f85546-717f-4634-9863-eda40a3b9f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Lampiran'])[1]/preceding::a[2]</value>
      <webElementGuid>d51fc9a0-4a71-4830-b68e-8c90f8b70d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf']/parent::*</value>
      <webElementGuid>f58bbb57-ec26-4996-80a5-c783ace54b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk2NTA4LnBkZg==']</value>
      <webElementGuid>b0106ffe-1c17-437e-ae96-7865a706c097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>2cf42d5a-c5ae-4c9a-a506-101da7c1a6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk2NTA4LnBkZg==' and (text() = 'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf' or . = 'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716796508.pdf')]</value>
      <webElementGuid>9b85012e-283c-448d-bb9c-253aed58672c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
