<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_P10_-_Measure_Performance_21_1435_Penelit_9b4010</name>
   <tag></tag>
   <elementGuidId>ed600486-bf18-48f5-a79e-234257429f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='existsFiles']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ms-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>080f4bac-ce15-4732-ac0c-6f86757f85ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk3OTc3LnBkZg==</value>
      <webElementGuid>f80c9781-a78b-4e28-a5e9-94f3e19d019a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>56edbbe6-892a-44c5-9abf-0599884ca42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf</value>
      <webElementGuid>521204f2-e5a4-4e0a-b177-6c720008785b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditEvaluasiPenelitian_A-21&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>b3da6e53-5bc1-42d8-a483-1c6a1f786d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='existsFiles']/div/a</value>
      <webElementGuid>15f4cbb3-3d61-4f9b-ba65-8678fc5581b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf')]</value>
      <webElementGuid>3460092f-4161-4265-9f63-4d50c7387ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[1]/following::a[1]</value>
      <webElementGuid>a46f0930-50eb-42c0-8554-39c3a777e531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan akhir penelitian (termasuklog book)'])[1]/following::a[1]</value>
      <webElementGuid>9566713e-c704-4118-826f-db3578b611a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::a[2]</value>
      <webElementGuid>bcb51965-cc4b-4579-b065-cebe2b8dfc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Lampiran'])[1]/preceding::a[2]</value>
      <webElementGuid>69e3d43a-b578-4242-9e5f-f3df777c24ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf']/parent::*</value>
      <webElementGuid>b6139a82-cae3-412d-bdd6-bb70ca4af807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk3OTc3LnBkZg==']</value>
      <webElementGuid>5938c04a-45b1-4bfd-848f-140d4228ce1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>a1f26c95-02d1-498d-80e4-b19af5c18cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/UDEwXy1fTWVhc3VyZV9QZXJmb3JtYW5jZV8yMV8xNDM1X1BlbmVsaXRpYW5fS2Vsb21wb2sxNzE2Nzk3OTc3LnBkZg==' and (text() = 'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf' or . = 'P10_-_Measure_Performance_21_1435_Penelitian_Kelompok1716797977.pdf')]</value>
      <webElementGuid>02e36099-7381-4477-8bb3-e02d63bdc197</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
