<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Files</name>
   <tag></tag>
   <elementGuidId>0c21e923-3729-40ae-956e-7ae644e486c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addFilesBtnPenelitianN-47</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFilesBtnPenelitianN-47']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Add Files&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>065278a2-3f3b-4831-af91-1bcf75c62caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb5cc7f3-5bcf-4b2b-9a1c-dec2439525e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFilesBtnPenelitianN-47</value>
      <webElementGuid>effe926c-2807-4010-9ccd-66c3e7fec941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>a641d3f5-9dfa-4d30-ab23-0029d95bc8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>a729aab5-3211-4dfd-a15d-afceda775447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFilesBtnPenelitianN-47&quot;)</value>
      <webElementGuid>0561f709-0c32-4aaf-8b26-88a10f970973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addFilesBtnPenelitianN-47']</value>
      <webElementGuid>ad20231e-1b87-4d92-afb9-488a2bfe4322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenelitian_N-47']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>76134b79-264e-410e-aeac-95a5e6139b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat (jika ada)'])[3]/following::button[1]</value>
      <webElementGuid>7c59262f-9c54-404b-b494-6818f227a92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Naskah/materi yang diberikan'])[1]/following::button[1]</value>
      <webElementGuid>500c21d1-d116-4742-9928-7437e50fce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[27]/preceding::button[1]</value>
      <webElementGuid>32bc2566-36b4-4c66-a6c7-b72c487d1001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>3bed4a36-75e5-4ad9-953e-deab44ad98c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'addFilesBtnPenelitianN-47' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>f6a97cff-8f8c-4ccb-820a-6cc3f6aa38fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
