<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mpdf_37_1435_Penelitian_Tridharma1716818360.pdf</name>
   <tag></tag>
   <elementGuidId>4494c57d-5c44-4856-ac27-88ae6039f9ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalEditPenelitian_I-37 > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.container > div.row > div.col-md-12 > div.mt-3.mb-3 > #existsFiles > div.file-item.d-flex.align-items-center.mb-2.border.rounded.p-3 > a.ms-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='existsFiles']/div/a)[33]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;mpdf_37_1435_Penelitian_Tridharma1716818360.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>345c89e1-a0ad-4b20-b8ee-ae4243427ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zN18xNDM1X1BlbmVsaXRpYW5fVHJpZGhhcm1hMTcxNjgxODM2MC5wZGY=</value>
      <webElementGuid>3282c65b-da2d-45b9-a575-f89090bc2668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>7b5255dd-4686-4e9e-8340-8406f3f87c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpdf_37_1435_Penelitian_Tridharma1716818360.pdf</value>
      <webElementGuid>ea55e29f-fdc2-4941-87d9-0bb696fd6e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditPenelitian_I-37&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>d13e88e4-321b-4c5e-b486-34e8f880c13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='existsFiles']/div/a)[33]</value>
      <webElementGuid>037ff9b7-e767-47d8-9733-494f23aa6e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mpdf_37_1435_Penelitian_Tridharma1716818360.pdf')]</value>
      <webElementGuid>a56a15f4-c64f-4714-b002-f03ec584ab23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[17]/following::a[1]</value>
      <webElementGuid>ba977b74-d19c-4f86-8b4f-eaa82eed496e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembar Pengesahan/bukti kegiatan yg disahkan atasan'])[1]/following::a[1]</value>
      <webElementGuid>d743bbe5-5972-45ed-8c4b-e64b6e99ad61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mpdf_37_1435_Penelitian_Tridharma1716818477.pdf'])[1]/preceding::a[1]</value>
      <webElementGuid>e88aaca6-ac5f-419c-b8f5-23679418f317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P10_-_Measure_Performance_37_1435_Penelitian_Tridharma1716818614.pdf'])[1]/preceding::a[2]</value>
      <webElementGuid>316f6637-0500-452d-ad1e-f324d7ededb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mpdf_37_1435_Penelitian_Tridharma1716818360.pdf']/parent::*</value>
      <webElementGuid>3d6a481f-9014-46e4-a777-7102e328e727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zN18xNDM1X1BlbmVsaXRpYW5fVHJpZGhhcm1hMTcxNjgxODM2MC5wZGY=']</value>
      <webElementGuid>292f85e5-fcde-4328-93a7-621684c68822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>fa82c3ff-f9dc-483a-a124-fa059c9c42a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zN18xNDM1X1BlbmVsaXRpYW5fVHJpZGhhcm1hMTcxNjgxODM2MC5wZGY=' and (text() = 'mpdf_37_1435_Penelitian_Tridharma1716818360.pdf' or . = 'mpdf_37_1435_Penelitian_Tridharma1716818360.pdf')]</value>
      <webElementGuid>9de095cb-996d-452f-9e08-fb1058ccb263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
