<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload                              _8f5048 (1)</name>
   <tag></tag>
   <elementGuidId>68f7f7aa-8e11-461b-8863-f9ece5b6e8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUploadPenelitianH-36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUploadPenelitianH-36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Upload Lampiran&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a55fa9c-8f9c-426d-9578-882be67fb875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2820b86b-c50c-46fc-9af9-ea283a417194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d61f9c44-5db2-45e3-966c-d7293cd75016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUploadPenelitianH-36</value>
      <webElementGuid>59b0f678-1ce7-4dbf-b3d9-a33e7c4b40c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload
                                                        Lampiran</value>
      <webElementGuid>1ef6bcae-6f84-42f5-9377-a3fdb97d25ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUploadPenelitianH-36&quot;)</value>
      <webElementGuid>449f2874-94de-44d1-af24-2de947da6910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUploadPenelitianH-36']</value>
      <webElementGuid>4fa11f17-345f-4554-a3be-c1d32115ee66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEditPenelitian_H-36']/div/div/div[3]/button[2]</value>
      <webElementGuid>42f8e810-b2ca-43e9-97e6-4941bbc80769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[16]/following::button[1]</value>
      <webElementGuid>126774c7-f903-4f97-b71f-c368acf14e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mpdf_36_1435_Pekerti_AA1716817871.pdf'])[1]/following::button[3]</value>
      <webElementGuid>e0b7872a-fd64-439d-ae62-4a6f817203a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[8]/preceding::button[1]</value>
      <webElementGuid>c6533878-968d-404b-93a3-3f2bd2a55bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[8]/preceding::button[1]</value>
      <webElementGuid>8fc2189d-530c-4267-9eb8-4c41d370f9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div[3]/button[2]</value>
      <webElementGuid>aeba979e-b64b-434d-b061-503e905ed09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnUploadPenelitianH-36' and (text() = 'Upload
                                                        Lampiran' or . = 'Upload
                                                        Lampiran')]</value>
      <webElementGuid>d3e7be45-dea0-4835-b62d-d9831dd3b018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
