<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload (1)</name>
   <tag></tag>
   <elementGuidId>d2f7433e-5c54-4ace-9d55-93b6b1cbfeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fileInputPenelitianH-36&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>File</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0a490116-19ab-48d9-aeb2-afb378e440b6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
