<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mpdf_35_1435_Pekerti_AA1716817508.pdf</name>
   <tag></tag>
   <elementGuidId>8b3e708a-62dc-453d-a31d-2f19280d7c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalEditPenelitian_H-35 > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.container > div.row > div.col-md-12 > div.mt-3.mb-3 > #existsFiles > div.file-item.d-flex.align-items-center.mb-2.border.rounded.p-3 > a.ms-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='existsFiles']/div/a)[28]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;mpdf_35_1435_Pekerti_AA1716817508.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6051a0b1-355d-44e6-a1ca-ba6c843edcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zNV8xNDM1X1Bla2VydGlfQUExNzE2ODE3NTA4LnBkZg==</value>
      <webElementGuid>5628e2de-2c68-45a8-8166-f5770be9ad4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>a6709f02-49b1-4b2a-a573-092879965a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpdf_35_1435_Pekerti_AA1716817508.pdf</value>
      <webElementGuid>f5782fa0-62c0-496d-8524-c143c80b8960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditPenelitian_H-35&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>a87189b4-e275-4b66-be8c-d20a6845d59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='existsFiles']/div/a)[28]</value>
      <webElementGuid>950cd757-8d11-4484-927e-f958d59e2e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mpdf_35_1435_Pekerti_AA1716817508.pdf')]</value>
      <webElementGuid>10325c6d-43a1-4eac-abb5-2bcac23fd56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[15]/following::a[1]</value>
      <webElementGuid>ca746f91-8de2-4892-af0b-26dcedd95a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat'])[1]/following::a[1]</value>
      <webElementGuid>a3625897-1083-46af-871f-5130151a5eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[15]/preceding::a[1]</value>
      <webElementGuid>f3cbeb22-b158-4f88-85a4-0dda8bba088e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mpdf_35_1435_Pekerti_AA1716817508.pdf']/parent::*</value>
      <webElementGuid>653b4695-a6c3-4444-95e5-d692affc6558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zNV8xNDM1X1Bla2VydGlfQUExNzE2ODE3NTA4LnBkZg==']</value>
      <webElementGuid>1f4ba440-54f3-4184-a6f4-274b095e283f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>3a3e1aed-92d0-4966-80c3-fb12023f6632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/bXBkZl8zNV8xNDM1X1Bla2VydGlfQUExNzE2ODE3NTA4LnBkZg==' and (text() = 'mpdf_35_1435_Pekerti_AA1716817508.pdf' or . = 'mpdf_35_1435_Pekerti_AA1716817508.pdf')]</value>
      <webElementGuid>6d236eb4-67c2-4928-adad-ac3ffd2275d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
