<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf</name>
   <tag></tag>
   <elementGuidId>aa17ec9a-3b3b-49f3-ae4c-f12b3f119799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalEditPenelitian_J-40 > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.container > div.row > div.col-md-12 > div.mt-3.mb-3 > #existsFiles > div.file-item.d-flex.align-items-center.mb-2.border.rounded.p-3 > a.ms-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='existsFiles']/div/a)[46]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8b3af56-7616-4f53-81f4-6317259157e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:8003/api/penelitian/get-lampiran/bXBkZl80MF8xNDM1X0p1cm5hbF9JbG1pYWgxNzE2ODIwMTc0LnBkZg==</value>
      <webElementGuid>e4866aa4-2ea1-4c46-ae5a-a3e6824dcf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>d88cf433-cb7a-40f2-81e3-eb072f41956f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf</value>
      <webElementGuid>da1b2404-9cb7-4098-b1e3-bfb7d09a3501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalEditPenelitian_J-40&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mt-3 mb-3&quot;]/div[@id=&quot;existsFiles&quot;]/div[@class=&quot;file-item d-flex align-items-center mb-2 border rounded p-3&quot;]/a[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>095a1725-c5ef-4d79-826e-616d1e2265fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='existsFiles']/div/a)[46]</value>
      <webElementGuid>9ec3c217-2b0c-4377-85b7-1cdf70ffde01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf')]</value>
      <webElementGuid>38f185ce-bf40-4065-af45-79b80d45731e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Files'])[20]/following::a[1]</value>
      <webElementGuid>6c3025d7-d126-4dfb-a303-e504e3f71058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Jenis Dokumen yang harus dilengkapi :'])[20]/following::a[1]</value>
      <webElementGuid>197038cd-f985-406e-8c71-60f96f4c1b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[20]/preceding::a[1]</value>
      <webElementGuid>e9e0c496-8057-4d57-94e9-cbe4481403fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf']/parent::*</value>
      <webElementGuid>51177b8e-8e0e-47a7-81e3-58903074ff00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:8003/api/penelitian/get-lampiran/bXBkZl80MF8xNDM1X0p1cm5hbF9JbG1pYWgxNzE2ODIwMTc0LnBkZg==']</value>
      <webElementGuid>2088b879-49b3-489d-8ee3-d0c2cc400c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>041bb1ac-072c-4256-ab52-867f6d26ac5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:8003/api/penelitian/get-lampiran/bXBkZl80MF8xNDM1X0p1cm5hbF9JbG1pYWgxNzE2ODIwMTc0LnBkZg==' and (text() = 'mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf' or . = 'mpdf_40_1435_Jurnal_Ilmiah1716820174.pdf')]</value>
      <webElementGuid>65f5c2e7-536e-48fd-8203-321e34717a06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
