<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata                                 _617843</name>
   <tag></tag>
   <elementGuidId>0ef8506c-f8fe-477f-865a-117db7aae183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typePasswordX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typePasswordX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kata\n                                            Sandi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07d65ace-a295-42ec-b280-6a4aae2bd8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>92e8d46e-9b1d-4d1b-9f6a-7d44852bd131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c4e787ab-1ea7-48b4-b3be-6007067323a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typePasswordX</value>
      <webElementGuid>cf3ff148-859d-44d7-861a-250afe98edbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow form-control form-control-lg border-dark</value>
      <webElementGuid>4412dda8-18aa-479f-8b3f-659d2a73566d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typePasswordX&quot;)</value>
      <webElementGuid>f7e45ad1-f971-451b-b26f-fd3b74b2676b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typePasswordX']</value>
      <webElementGuid>9bb9356e-3c0c-447e-8749-5df401b44a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>98d2b53b-39b2-4ec5-99f8-b9af0e2952fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'typePasswordX']</value>
      <webElementGuid>7c63ac5e-4ea5-4b9a-8791-64d4d834848d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
