<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload</name>
   <tag></tag>
   <elementGuidId>ebbb16da-8d52-427a-9e23-ebe72156c4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fileInputPenelitianL-43&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>File</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0231b4a9-f8ca-40c3-a55f-afdca116b610</webElementGuid>
   </webElementProperties>
</WebElementEntity>
