<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nama Kegiatan</name>
   <tag></tag>
   <elementGuidId>4b0640cf-8c2f-4a24-81d9-e78936e85cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPenunjang_N > div.modal-dialog.modal-dialog-centered > div.modal-content > div.modal-body > form > div.mb-3 > label.form-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalPenunjang_N']/div/div/div[2]/form/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog[name=&quot;A. Bimbingan Akademik (perwalian/penasehat akademik)&quot;i] >> label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8f8ea2ae-dc39-4a21-a28c-413a37553adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>80b3df31-e5e6-47b2-b79f-260105330087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>bbd35b95-09ed-4751-a578-1ab606caf1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Kegiatan:</value>
      <webElementGuid>ec58356c-6f60-4c67-89ac-8c8492c954e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPenunjang_N&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>63b43ca2-e69e-4cda-a23f-a185edca9d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_N']/div/div/div[2]/form/div/label</value>
      <webElementGuid>3f162cac-9e13-4c8d-ae38-04d988a3a5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N. Reviewer Jurnal Ilmiah , Proposal Hibah dll'])[1]/following::label[1]</value>
      <webElementGuid>28b17dd1-cabb-4981-8c52-90f77dc2dccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[13]/following::label[1]</value>
      <webElementGuid>3376d2a9-5a00-4e10-b475-e69766201e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[14]/preceding::label[1]</value>
      <webElementGuid>7ea90a6a-deb1-4bfc-8280-ea16f90ad526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div/div/div[2]/form/div/label</value>
      <webElementGuid>0bfc421e-2ef3-4c3c-aebf-73df8af2f7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nama Kegiatan:' or . = 'Nama Kegiatan:')]</value>
      <webElementGuid>3810654b-209a-474f-85ba-17d08d063cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
