<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Jumlah Mahasiswa</name>
   <tag></tag>
   <elementGuidId>3e1b657f-8f4f-4b51-be92-12ec8a930ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalPenunjang_B']/div/div/div[2]/form/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalPenunjang_B >> internal:text=&quot;Jumlah Mahasiswa:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>daeab11a-c720-4527-aead-1da4e5e4e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>jumlah_mahasiswa</value>
      <webElementGuid>685ab987-5edf-432e-821b-5ebd11540716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>efe76183-3c5f-426a-92d2-fe7d34d29b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jumlah Mahasiswa:</value>
      <webElementGuid>1730c0cd-726f-4554-a1cb-bda9c501535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPenunjang_B&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;mb-3&quot;]/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>a9869222-23cf-4fde-98c5-30b36d4b6d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPenunjang_B']/div/div/div[2]/form/div[2]/label</value>
      <webElementGuid>593eda8c-f89b-4404-b727-0a3ccd58945a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Kegiatan:'])[2]/following::label[1]</value>
      <webElementGuid>9f80a46b-23e3-45d5-a08e-a778087b8bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B. Bimbingan dan Konseling'])[1]/following::label[2]</value>
      <webElementGuid>c43655d8-e76e-4673-a894-2118c20f519e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[2]/preceding::label[1]</value>
      <webElementGuid>221fbdb7-1073-4173-b074-9d50af4d4039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C. Pimpinan Pembina Unit Kegiatan Mahasiswa'])[1]/preceding::label[1]</value>
      <webElementGuid>409e6e58-5ac8-47d8-889e-6e953e5234bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div[2]/form/div[2]/label</value>
      <webElementGuid>73e9b999-0ef6-48d5-926d-a98cc394ad52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Jumlah Mahasiswa:' or . = 'Jumlah Mahasiswa:')]</value>
      <webElementGuid>7e6c936a-dc8e-4802-9761-be88de40b0f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
