<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Lampiran</name>
   <tag></tag>
   <elementGuidId>2c7a0165-32f3-4bbe-96e1-7645fc1936e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tablePenelitian-G > tbody > tr > td:nth-of-type(9) > button.btn.btn-primary.mr-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[56]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 Test Penelitian G 1 Lampiran belum diupload. Hasil Akhir Mandiri Anggota 2.00 Tambah Lampiran&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed284b69-248c-4605-a1ad-b65537623d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd32b49b-9b92-4e43-9178-4eb3f9fe4319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-1</value>
      <webElementGuid>45f62fdf-2578-40d1-839a-2ac69a8533f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d83322cd-a3e6-4e84-aa28-47ccf77653ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modalEditPenelitian_G</value>
      <webElementGuid>a7671d9d-df2e-4866-bfea-3cc912d1cca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Lampiran</value>
      <webElementGuid>b83dc6de-4efb-4b88-b1a7-0fd060c3c9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablePenelitian-G&quot;)/tbody[1]/tr[1]/td[9]/button[@class=&quot;btn btn-primary mr-1&quot;]</value>
      <webElementGuid>0d50a890-474c-4988-a081-f8da593141fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[56]</value>
      <webElementGuid>98f98ff3-13f2-4288-af64-c843a590d95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablePenelitian-G']/tbody/tr/td[9]/button</value>
      <webElementGuid>5d1faa99-317e-40ca-8dba-a588f1972812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anggota'])[1]/following::button[1]</value>
      <webElementGuid>acce94be-9d1d-4fe1-8019-cb594a59db2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandiri'])[5]/following::button[1]</value>
      <webElementGuid>fefcb40f-b2ea-449f-9048-f5f23580b1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Penelitian G 2'])[1]/preceding::button[1]</value>
      <webElementGuid>5810acde-bc26-4f9c-9b1d-a738dcc03855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lampiran belum diupload.'])[2]/preceding::button[1]</value>
      <webElementGuid>8b33f55e-fe7a-4eb0-80a3-9739cadc0f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/table/tbody/tr/td[9]/button</value>
      <webElementGuid>7e887714-c38c-4428-ad89-2366d1d35a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah Lampiran' or . = 'Tambah Lampiran')]</value>
      <webElementGuid>ff113b7f-64ae-49b8-afb4-c3e57e4efa40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
